### ISSUE TITLE
"No se puede cargar la imagen"

### ISSUE THREAD

**Issue by ThePaste** [SrRapero720/WATERFrAMES#10]
Estoy usando el mod en aternos junto con otros 58 y me indica que "no se puede cargar la imagen", ¿alguien podría decirme a que es debido este error?
![2023-06-21_17 02 45](https://github.com/SrRapero720/waterframes/assets/123248949/20c3e18f-f800-4317-97ad-77c158b50e07)

**Comment by SrRapero720** [comment]
Estás utilizando la 1.2.0. esa versión perdió totalmente el soporte de YouTube. Actualiza a la 1.3.0b
