### ISSUE TITLE
[BUG] Log spam when opening GUI with REI installed [Fabric 1.20.1/0.16.0]

### ISSUE THREAD

**Issue by pokesmells** [SrRapero720/WATERFrAMES#100]
https://github.com/user-attachments/assets/36805f5c-aca0-48da-8d61-5da0eeb07717

https://mclo.gs/Q08hpxZ

Simply open the GUI and get spammed with log entries.

**Comment by SrRapero720** [comment]
Issue by REI https://github.com/shedaniel/RoughlyEnoughItems/issues/1685
i will mark REI as a incompatible mod in future updates if the logpspam isnt solved
