### ISSUE TITLE
[forge 1.20.1] crash on clicking TV

### ISSUE THREAD

**Issue by thvless** [SrRapero720/WATERFrAMES#101]
client crashes when clicking a tv thats already playing media, probably due to embeddium++ option of hide jei until searching

[latest.log](https://github.com/user-attachments/files/16482784/latest.log)
[crash-2024-08-03_21.18.02-client.txt](https://github.com/user-attachments/files/16482785/crash-2024-08-03_21.18.02-client.txt)

**Comment by SrRapero720** [comment]
its caused by JEI, report that to JEI
