### ISSUE TITLE
Rotation locking [1.20.1]

### ISSUE THREAD

**Issue by 07Productions** [SrRapero720/WATERFrAMES#102]
Trying to rotate my image 90 degrees but it locks at 91.43 degrees

![image](https://github.com/user-attachments/assets/5b326f3a-d1f9-49b1-aef3-64e42a7fc35c)

**Comment by SrRapero720** [comment]
right click on it and type it directly

**Comment by SrRapero720** [comment]
what is the name of the texture pack?

**Comment by 07Productions** [comment]
> what is the name of the texture pack?

Yuushya, also thank you for the help, I feel stupid that I didn't think of right clicking!
