### ISSUE TITLE
A suggestion for improvement

### ISSUE THREAD

**Issue by GYT0106** [SrRapero720/WATERFrAMES#103]
I feel like it needs to be fixed: these waterframes shouldn't require cheat permissions to change the playback, I made a waterframe in hardcore, but since there are no cheat permissions, I can't even set the content to play for the waterframe, hopefully improve

**Comment by SrRapero720** [comment]
check waterframes config, by default everyone can edit frames, so i assume that is a bug

**Comment by GYT0106** [comment]
https://github.com/user-attachments/assets/eec98899-fbcf-4ce3-b6e8-f2030b182b79



> 检查 waterframes 配置，默认情况下每个人都可以编辑帧，所以我认为这是一个错误

I tried uninstalling the config file and reinstalling the mod, but it still doesn't work

**Comment by GYT0106** [comment]
@SrRapero720  I still can't use a waterframe without cheat permissions,you can watch my video

**Comment by SrRapero720** [comment]
bruh thats not a permissions issue, that is a bug, send me your logs please

**Comment by GYT0106** [comment]
> 这不是权限问题，这是一个错误，请将您的日志发送给我

OK，
[2024-08-08-6.log.gz](https://github.com/user-attachments/files/16555067/2024-08-08-6.log.gz)
I'll upload the log file

**Comment by GYT0106** [comment]
> 这不是权限问题，这是一个错误，请将您的日志发送给我

[2024-08-08-5.log.gz](https://github.com/user-attachments/files/16556115/2024-08-08-5.log.gz)

**Comment by SrRapero720** [comment]
this issue must be fixed
