### ISSUE TITLE
Crashing after latest update

### ISSUE THREAD

**Issue by andriihorpenko** [SrRapero720/WATERFrAMES#104]
Simply opening any TV leads to a crash of a dedicated server.
[crash-2024-08-19_16.55.19-server.txt](https://github.com/user-attachments/files/16661165/crash-2024-08-19_16.55.19-server.txt)

**Comment by andriihorpenko** [comment]
By the way, (Neo)Forge discourages usage of `@OnlyIn` annotation, as it is not meant to be used by modders.
https://github.com/SrRapero720/waterframes/blob/de4816a31e4414ed779af0e25fbff6ac44c3cc1a/src/main/java/me/srrapero720/waterframes/common/block/entity/DisplayTile.java#L43
This basically strips that line from the compiled code, which leads to the crash above.

**Comment by Laurentzius** [comment]
same problem
on singleplayer all ok but crashes on server

**Comment by SrRapero720** [comment]
Issue has been fixed.

**Comment by SrRapero720** [comment]
> By the way, (Neo)Forge discourages usage of @OnlyIn annotation, as it is not meant to be used by modders.

I am not sure what are you trying to tell me, if i use it was for a very good reason :P
anyway, issue has nothing to do about the annotation usage, was the creativecore GuiLayer thing.
