### ISSUE TITLE
Crash on Forge 1.20.1 "Cannot invoke"

### ISSUE THREAD

**Issue by NachoIannizzotto** [SrRapero720/WATERFrAMES#106]
[crash-2024-08-20_01.08.13-client.txt](https://github.com/user-attachments/files/16668875/crash-2024-08-20_01.08.13-client.txt)

When trying to interact with a Television from Watermedia Mod, the UI opens invisible and if I press escape or E for inventory, the game crash.

Exception: The game crashed whilst keypressed event handler
Error: java.lang.NullPointerException: Cannot invoke "team.creative.creativecore.common.gui.IGuiParent.closeTopLayer()" because the return value of "team.creative.creativecore.common.gui.GuiParent.getParent()" is null

**Comment by SrRapero720** [comment]
i invoke you to update the mod

**Comment by NachoIannizzotto** [comment]
> i invoke you to update the mod

I had the mod updated before and downgraded to check if it was the issue
