### ISSUE TITLE
Crashing server on Remote Control use

### ISSUE THREAD

**Issue by oskarbukovsky** [SrRapero720/WATERFrAMES#117]
[debug.log](https://github.com/user-attachments/files/16923883/debug.log)
[crash-2024-09-09_00.21.55-server.txt](https://github.com/user-attachments/files/16923884/crash-2024-09-09_00.21.55-server.txt)
Minecraft 1.20.1
Forge 47.3.
Waterframes 2.1.3

**Comment by SrRapero720** [comment]
fixed
