### ISSUE TITLE
Using Remote Control without press Shift causes a Crash

### ISSUE THREAD

**Issue by FerHamid** [SrRapero720/WATERFrAMES#119]
If the Remote Control is not bound, the game crashes when I Right-Click without pressing Shift on a screen/projector.

[crash-2024-09-11_23.13.20-client.txt](https://github.com/user-attachments/files/16973876/crash-2024-09-11_23.13.20-client.txt)

Minecraft 1.21.1
WaterFrames 2.1.4 [Fabric]
Fabric Loader 0.16.5

**Comment by SrRapero720** [comment]
why i am not surpriced....

**Comment by SrRapero720** [comment]
fixed
