### ISSUE TITLE
Founded directories but custom loading gif is missing

### ISSUE THREAD

**Issue by Dorko316** [SrRapero720/WATERFrAMES#120]
I recently tried adding Waterframes into my modpack, but Minecraft keeps crashing on startup. Below is the final lines of the log before it crashes. I'm in Forge for Minecraft 1.20.1.

[23:49:23] [Forge Version Check/INFO]: [watermedia] Starting version check at https://forge.curseupdate.com/869524/watermedia
[23:49:23] [Worker-ResourceReload-0/ERROR]: Founded directories but custom loading gif is missing

Any idea how to fix it?
Here's the full log if it helps: [latest.log](https://github.com/user-attachments/files/17088347/latest.log)

Let me know if you need any more information.

**Comment by SrRapero720** [comment]
Never assume errors when you see a "error" log line
that error says watermedia can't find the custom loading gif for waterframes, so instead will use the default loading gif.

i have no idea why your modpack crashes, watermedia has no culprit, what i see is you're using optifine, so may try removing it

**Comment by Dorko316** [comment]
That worked! Optifine was the issue. Unfortunately now it crashes every time I right-click on a Waterframe device. At least this time it generated a crash report.

[crash-2024-09-22_15.57.46-server.txt](https://github.com/user-attachments/files/17091300/crash-2024-09-22_15.57.46-server.txt)

Sorry if I'm being obnoxious or anything. It's my first time making a modpack of this size. My friends and I are really hoping to use this instead of Web Display and I'm not sure where else to go for help.

**Comment by SrRapero720** [comment]
@Dorko316 i released a new update fixing that crash
Update the mod

**Comment by Dorko316** [comment]
That did it! Thanks again for all the help!
