### ISSUE TITLE
1.18.2 version 2.1.5 - can't load anything on youtube on the television google drive works fine tho

### ISSUE THREAD

**Issue by AzzyDR** [SrRapero720/WATERFrAMES#121]
i tried to load a video from youtube and its broken it refuses to load anything on youtube at all
yesterday it was having issues but today it refuses to work entirely

![2024-09-24_22 23 45](https://github.com/user-attachments/assets/cc2c75ba-b05e-4364-bef9-77bd13508d61)
![2024-09-24_22 23 46](https://github.com/user-attachments/assets/d402e85c-bf0e-404d-a2f6-78af94ecfecd)

**Comment by Dorko316** [comment]
Happening in 1.20.1 too.

**Comment by SrRapero720** [comment]
stop making duplicates of issues
the proper issue to reports is https://github.com/WaterMediaTeam/watermedia/issues/92
