### ISSUE TITLE
youtube links not working

### ISSUE THREAD

**Issue by EPICbendy** [SrRapero720/WATERFrAMES#122]
im in a server with a few friends and when i put a youtube link it it shows nothing and says "status: could not download image" imagur links work though. im on forge 1.20.1

**Comment by EPICbendy** [comment]
imagur links work though.

**Comment by SkyRunner55** [comment]
its seem to append also in neoforge 1.21.1

**Comment by arcmega** [comment]
Same problem here.

**Comment by Dorko316** [comment]
I'm having the same issue as well.

**Comment by Ryuushen** [comment]
Having same issue on 1.20.1

**Comment by SrRapero720** [comment]
stop making duplicates of issues
i am aware and the proper issue is https://github.com/WaterMediaTeam/watermedia/issues/92
