### ISSUE TITLE
Crasher 

### ISSUE THREAD

**Issue by joaoespanhol** [SrRapero720/WATERFrAMES#124]
Log: https://mclo.gs/05E47pv

**Comment by SrRapero720** [comment]
update the mod

**Comment by joaoespanhol** [comment]
Last version no work video.
@SrRapero720 
![image](https://github.com/user-attachments/assets/9310c5da-f6f7-4e9f-b017-bf943278a766)


exemple link video: https://www.youtube.com/watch?v=C-vTjGfsQ0o

**Comment by SrRapero720** [comment]
update the mod yet again (Watermedia)

**Comment by joaoespanhol** [comment]
> update the mod yet again (Watermedia)

I have last version., same problem

**Comment by joaoespanhol** [comment]
@SrRapero720 
update the mod yet again (Watermedia)

I have last version., same problem

**Comment by SrRapero720** [comment]
ok wait for a new release
