### ISSUE TITLE
"waterframes requires watermedia below 2.1"

### ISSUE THREAD

**Issue by vinnyg0621** [SrRapero720/WATERFrAMES#131]
my game was telling me that watermedia needs an update, and they were right. but waterframes needs watermedia _below 2.1_??! that is dumb.
so please fix this issue where newer watermedia versions crash, thanks!
![Screenshot 2024-10-27 224830](https://github.com/user-attachments/assets/d4081447-40cc-4da1-9297-f1e2e9083d77)

[crash report](https://mclo.gs/rS56OoQ)

**Comment by SrRapero720** [comment]
you're dumb
downgrade watermedia until you see waterframes gets updated

**Comment by vinnyg0621** [comment]
> you're dumb downgrade watermedia until you see waterframes gets updated

oh...
alright I'll downgrade it for now.
