### ISSUE TITLE
Incompatibility Error with "Stellarity" Reference, but Mod Not Installed

### ISSUE THREAD

**Issue by Luxorift** [SrRapero720/WATERFrAMES#133]
Hello, I’m experiencing an incompatibility issue in my Minecraft client that references the mod Stellarity as causing a conflict with WaterFrames, even though Stellarity is not installed in my mod list. Below are the details and exact error message.

Specifications:
Minecraft Version: 1.20.1
WaterFrames Version: 2.1.7
Other Installed Mods: (I’m attaching a list of the installed mods in case one of them is causing the conflict)
Operating System: Windows
Error Message:
Exception caught during firing event: Mod 'mr_stellarity (Stellarity)' is not compatible with 'WATERFrAMES' because it breaks picture rendering, overwrites Minecraft core shaders and isn't possible work around that. Please remove it.
me.srrapero720.waterframes.WFRegistry$UnsupportedModException: Mod 'mr_stellarity (Stellarity)' is not compatible with 'WATERFrAMES' because it breaks picture rendering, overwrites Minecraft core shaders and isn't possible work around that. Please remove it.
Attached Files:
latest.log: Full log from my Minecraft client.
Crash Report: Details of the error and crash cause.
Troubleshooting Steps Taken:
Checked my mod folder and confirmed Stellarity is not installed.
Tried disabling other mods related to graphics, visual effects, and shaders, but the issue persists.
Verified that all mods are updated to the latest compatible versions for Minecraft 1.20.1.
Help Request:
Could this issue be caused by another mod triggering a similar conflict to Stellarity? If possible, I’d like to avoid removing WaterFrames. Any guidance would be appreciated.

Thank you for your time and assistance!
![Captura de pantalla 2024-10-29 224031](https://github.com/user-attachments/assets/4d4def42-d6f8-450d-afc7-19e428d72654)
[latest.log](https://github.com/user-attachments/files/17565766/latest.log)
[crash-2024-10-29_22.31.43-fml.txt](https://github.com/user-attachments/files/17565769/crash-2024-10-29_22.31.43-fml.txt)

**Comment by Luxorift** [comment]
Pense que hablabas ingles
aqui el error en español :D
y si puedes responderme en español te lo agradeceria :D
Descripción:
Hola, estoy experimentando un problema de incompatibilidad en mi cliente de Minecraft que menciona el mod Stellarity como causante de un conflicto con WaterFrames, aunque Stellarity no está instalado en mi lista de mods. A continuación, detallo los pasos y el mensaje de error exacto:

Especificaciones:
Versión de Minecraft: 1.20.1
Versión de WaterFrames: 2.1.7
Otros mods instalados: (adjunto una lista de los mods que tengo instalados, ya que algunos podrían estar causando el conflicto)
Sistema operativo: Windows
Mensaje de Error:
plaintext
Copiar código
Exception caught during firing event: Mod 'mr_stellarity (Stellarity)' is not compatible with 'WATERFrAMES' because it breaks picture rendering, overwrites Minecraft core shaders and isn't possible work around that. Please remove it.
me.srrapero720.waterframes.WFRegistry$UnsupportedModException: Mod 'mr_stellarity (Stellarity)' is not compatible with 'WATERFrAMES' because it breaks picture rendering, overwrites Minecraft core shaders and isn't possible work around that. Please remove it.
Archivos adjuntos:
latest.log: Incluye el log completo del cliente de Minecraft.
Crash report: Detalles del error y la causa del crasheo.
Pasos realizados para diagnosticar el problema:
Revisé mi carpeta de mods y confirmé que Stellarity no está instalado.
Intenté desactivar otros mods relacionados con gráficos, efectos visuales y shaders, pero el error persiste.
Verifiqué que todos los mods están actualizados a sus versiones más recientes compatibles con Minecraft 1.20.1.
Solicitud de ayuda:
Me gustaría saber si este problema puede ser causado por otro mod que esté generando un conflicto similar al de Stellarity o si hay alguna forma de evitar esta incompatibilidad sin tener que eliminar WaterFrames.

¡Gracias por tu tiempo y ayuda!

**Comment by Luxorift** [comment]
Antes funcionaba todo a la perfección, pero creo que la última actualización de WaterFrames está causando este error. Si pudieras solucionarlo, te lo agradecería mucho.

**Comment by SrRapero720** [comment]
ya quedo arreglado, actualiza a la version con la A

**Comment by Luxorift** [comment]
okey muchas gracias :D
