### ISSUE TITLE
VLC not loaded? on zorin OS(based on Ubuntu)

### ISSUE THREAD

**Issue by KiaantheGamer** [SrRapero720/WATERFrAMES#139]
![Screenshot from 2024-11-13 21-25-00](https://github.com/user-attachments/assets/cce79a5f-01a4-4717-81d7-638feeafd07d)
 
AstralRinth(modrinth app for cracked mc)
Version: 1.21.1
Vlc installed from Flathub

![Screenshot from 2024-11-13 21-37-30](https://github.com/user-attachments/assets/9b7499e0-8cbd-41cd-b22b-dac2169d6e31)

**Comment by matthiasdevreede** [comment]
Issue is addressed in https://discord.com/channels/486853064284831744/1243569886253551686/1306040996731162725
(Aka, SrRapero's discord)
🛠️ Shows a picture saying "FAILED TO LOAD VLC"
(🐧) Install VLC, it haves to be installed manually
:mac: [MacOS](https://www.videolan.org/vlc/download-macosx.html) (pick universal binaries)
🐧 [Linux](https://www.videolan.org/vlc/download-debian.html) (NOTE: flatpack and snap aren't supported)
