### ISSUE TITLE
Game's Master Volume Slider Does Not Affect Waterframe Video Volume

### ISSUE THREAD

**Issue by clebsz** [SrRapero720/WATERFrAMES#14]
This issue leads to frustrating situations where, for example, a 512-meter range video plays loudly, and muting it requires muting the entire game through the system's mixer.

Adding a separate volume slider specifically for waterframe videos in the sound settings would be an excellent solution.

**Comment by SrRapero720** [comment]
loud sound on long distances is a knowed issue (by watermedia)
about sliderbar... i'm gonna put waterframes volume on master volume (or in blocks volume) on next major update WF 2.0.0

**Comment by SrRapero720** [comment]
Bug was fixed, enhancement was planned.
