### ISSUE TITLE
[Question] Open video from google drive failed.

### ISSUE THREAD

**Issue by NumpaMC** [SrRapero720/WATERFrAMES#140]
I went into google drive and selected a video, copied the link and pasted it into the mod link and clicked save, but after spinning a few times it said the result was null. "status: null"
OS: Windows 11 pro for Workstation
Version mod: All the latest.
Minecraft 1.20.1

**Comment by espectroplasma636** [comment]
How do you fix that issue? It's not working for me.

**Comment by NumpaMC** [comment]
> How do you fix that issue? It's not working for me.

Go to google drive, click on the three dots of the video you want, hover your mouse over to share, it will show 2 more lines, click share, right at general access, click on restrict, then change from restrict to anyone with the link. Sorry for my late reply.
