### ISSUE TITLE
`NoSuchMethodError` due to binary incompat with CreativeCore

### ISSUE THREAD

**Issue by andriihorpenko** [SrRapero720/WATERFrAMES#145]
## Description
CreativeCore has changed signature of `WidgetURLTextField#setMaxStringLength` function, making it binary incompatible with WaterFrames.

## Exception
```ex
java.lang.NoSuchMethodError: 'void me.srrapero720.waterframes.common.screens.widgets.WidgetURLTextField.setMaxStringLength(int)'
	at me.srrapero720.waterframes.common.screens.widgets.WidgetURLTextField.<init>(WidgetURLTextField.java:22) ~[waterframes-834607-5970180_mapped_official_1.20.1.jar%23456!/:FORGE-mc1.20.1-v2.1.8] {re:classloading}
```

## Potential solution
Rebuilding and republishing the mod should do it, but also changing minimum required version of CreativeCore in `mods.toml`.

## Metadata
**CreativeCore version**: 2.12.26 (released yesterday)
**WaterFrames version**: 2.1.8

**Comment by SrRapero720** [comment]
i am aware, downgrade CreativeCore version (to the `2.12.25`) for now

**Comment by SrRapero720** [comment]
solved
