### ISSUE TITLE
Mod crashing with claims of a non existent mod

### ISSUE THREAD

**Issue by Aerin-Hunter** [SrRapero720/WATERFrAMES#147]
I've been using waterframes for a while now, as it's been really useful in both Single Player and Multiplayer for me and my friends. After a recent update, the mod started crashing, so I begun investigating. I uninstalled and reinstalled older versions of the mod, of which a majority kept crashing. What's strange is, under one instance, the pack stated that it was conflicting with another mod called Stellarity. I am aware that this mod has been discussed about prior, and has been marked as not being supported with this mod. The problem is we don't HAVE Stellarity installed either on SP or MP, so i'm confused as to what's causing the conflict. I shall post the modlist as well as the error message which shows the conflict
[Age of Automation mods.txt](https://github.com/user-attachments/files/18168879/Age.of.Automation.mods.txt)
[crash-2024-12-17_16.30.56-fml.txt](https://github.com/user-attachments/files/18168895/crash-2024-12-17_16.30.56-fml.txt)

**Comment by SrRapero720** [comment]
my friend _never make a bug report of an older version_. your crash was already solved in latest versions
![image](https://github.com/user-attachments/assets/e9213a7f-2dd9-47d8-9154-5d564b654ec6)

if you find a problem report it with the crash from latest versions.

**Comment by Aerin-Hunter** [comment]
I didn't get the warning on the 2.1.7a version, only the 2.1.7 version, hence why I wasn't sure if i was missing something. I do have a crash report from the current version as well (which I did forget to post on the last post). Here's a recent report with 2.1.7a and watermedia 2.1.8
[crash-2024-12-17_19.41.16-server.txt](https://github.com/user-attachments/files/18170571/crash-2024-12-17_19.41.16-server.txt)

**Comment by SrRapero720** [comment]
see #145

**Comment by Aerin-Hunter** [comment]
That's worked perfectly, thank you so much for your help! And thanks for a fantastic mod
