### ISSUE TITLE
Unable to create or open worlds in 1.20.1

### ISSUE THREAD

**Issue by OutrageouslyIcy** [SrRapero720/WATERFrAMES#148]
Running into issues with the latest version of the mod, opening worlds gets me stuck with a blank screen, tried downgrading creative core and still no luck.

[latest.log](https://github.com/user-attachments/files/18172739/latest.log)

**Comment by SrRapero720** [comment]
was not related to my mod

**Comment by vinnyg0621** [comment]
i'm having the same problem, so which mod is it related to then?
