### ISSUE TITLE
Black Screens in Minecraft Server 

### ISSUE THREAD

**Issue by Luizoba** [SrRapero720/WATERFrAMES#15]
Hey, I'm having a issue with my friends in a online server. When I try to put the picture frame, the link don't load, it's just a black screen for no reason. There's times the picture frame works fine, but if I break the picture frame and replace in another block (or the same), I got the same issue from before. I'm also using Waystone mod, when I teleporte to another place, and go back to my home, the pictures got black screen again.

Minecraft Version: 1.18.2
Mod Version: 1.3.1d
Forge Version: 40.2.9
And I'm using Watermedia-1.2.13

**Comment by SrRapero720** [comment]
update to watermedia 1.3.1e and watermedia 1.3.x
https://www.curseforge.com/minecraft/mc-mods/waterframes/files/4620637
https://legacy.curseforge.com/minecraft/mc-mods/watermedia/files/4652124
