### ISSUE TITLE
Annoying bug

### ISSUE THREAD

**Issue by Hoppeee** [SrRapero720/WATERFrAMES#16]
the Picture Frame item is no longer interacting with the redstone and this is disturbing a project of mine

**Comment by SrRapero720** [comment]
enable it on serverconfig

**Comment by SrRapero720** [comment]
![image](https://github.com/SrRapero720/waterframes/assets/29090346/886dfcb6-e13c-4a56-89f7-bfa58a3317b9)

**Comment by Hoppeee** [comment]
how can i get into serverconfig?

**Comment by Hoppeee** [comment]
mine only has these options

https://prnt.sc/vfvE4bxJ7OJi

**Comment by SrRapero720** [comment]
depends on where are you running WF
on client: `.minecraft/saves/<myworld>/serverconfig/waterframes.toml`
on server: `/root/<myworld>/serverconfig/waterframes.toml`

NOTE: ALL MY MODS (except WATERMeDIA) uses ServerConfig to store config, so server admins can change client config for anyone.

**Comment by SrRapero720** [comment]
that config is pretty OLD, from old rustic waterframes, you can delete it

**Comment by Hoppeee** [comment]
"disableUsageForPlayers" that I should activate?

**Comment by SrRapero720** [comment]
![image](https://github.com/SrRapero720/waterframes/assets/29090346/9e0ef15d-123d-412f-bcef-312c8d50c0a1)
