### ISSUE TITLE
New Update Crash

### ISSUE THREAD

**Issue by bazmetal** [SrRapero720/WATERFrAMES#17]
Hi there, I wonder if you could please help me.

So on Minecraft Java 1.19.2, I am having a constant crash problem on the new version of Water Frames 1.4.0a, on an area in my world the game crashes and exits, this does not happen at all in version 1.3.1e. The area has a lot of stuff built in it, I thought chisels and bits caused the problem but I removed the mod and the problem still persists.

The error I am getting on Minecraft launcher states: An unexpected issue has occurred and the game has crashed. This crash may be resolved by allocating additional memory in the configuration for this version of Minecraft Java. Exit Code -805306369.

It seems like this new update is more ram demanding and I cannot use this update as I will not be able to allocate any more ram, I am already allocating 8gb, I have also tried allocating 10gb at the most and the crash still happens.

**Comment by SrRapero720** [comment]
can you send me your logs? i'll investigate it fast i can

**Comment by bazmetal** [comment]
Thanks for your reply, where do I get the log?

**Comment by SrRapero720** [comment]
Enter to you game folder, search "logs" folder and send me your latest.log located in that folder
use [this](https://gist.github.com) site to upload, copy the URL and send it here

**Comment by bazmetal** [comment]
Ok I will do that later today, thank you

**Comment by bazmetal** [comment]
https://gist.github.com/bazmetal/5d1383a2a8474c8120478af4ce02f319

Please let me know if you can view this

**Comment by SrRapero720** [comment]
I see your error Is caused by a wrong GUI scale, maybe modified by other mod, try to enter to your game folder, options.txt and search guiscale option and set it to any other value (3 for example)

**Comment by bazmetal** [comment]
Hey thanks for looking into that for me. I will try it soon and let you know what happens

**Comment by bazmetal** [comment]
Hi SrRapero, it changed the menu text size and icons, but that is all it did. After when you choose your world and the square graphic with the percentage passes the game still crashes when it then says loading world. And while this is frozen you have no choice but to click the left mouse button and it then says something like Java platform SE binary is not responding.

**Comment by bazmetal** [comment]
Also, it says with the mojang help link the error comes with that it can be difficult to pinpoint the source, often it can be game running out of memory, remove resource packs (which i have tried) and to check JVM arguments. The JVM arguments I have for my 1.19.2 forge are: -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M do you think there could be something wrong here?

**Comment by SrRapero720** [comment]
Resendme your logs.
i receive more bug reports on 1.19.2, so probably build Is corrupted
I'll launch a rebuild versión with a minor bugfix

**Comment by bazmetal** [comment]
Ah ok. Thank you SrRapero.

Here is the latest log https://gist.github.com/bazmetal/d0a8b28ba59e959c5deb1bf68fd3a885

**Comment by SrRapero720** [comment]
You resend me the same log? Doesn't show anyrhing different
And log date Is the same

**Comment by bazmetal** [comment]
Oh sorry, I looked at my logs and I copied the older one again! LOL.

This should be the latest one: https://gist.github.com/bazmetal/e3ed2135f1b1e3d995f45ba76c582fc7

**Comment by SrRapero720** [comment]
![2023-07-27_18h45_50](https://github.com/SrRapero720/waterframes/assets/29090346/f304bae6-0d9b-4303-8e3b-7a86567445f9)
Sadly update is delayed by CURSEFORGE (doing virus scans for all mods)
aparently is a platform bug.


btw, you can try downloading GH release if issue was solved
https://github.com/SrRapero720/waterframes/releases/tag/1.19.2-1.4.0b

**Comment by bazmetal** [comment]
Ok I'll wait for that thank you. I tried the 1.4.0b you linked to me to try, it is still crashing.

My log is here if it helps: https://gist.github.com/bazmetal/e01b7e48774d4045989a073d4cdca6e6

**Comment by bazmetal** [comment]
I think the one now on curseforge is the same. It still crashes.

**Comment by SrRapero720** [comment]
curseforge and github release is the same 
i can't replicate the issue and your logs doesn't show more than errors trying to patch pictures (normal) and a  "can't keep up". so is probably an issue from watermedia

 i need you do something different to get the real crash
open your launcher -> settings -> show game output
![2023-07-28_12h03_31](https://github.com/SrRapero720/waterframes/assets/29090346/3ac9b221-9158-4b88-a847-6409451868f4)
![2023-07-28_12h04_20](https://github.com/SrRapero720/waterframes/assets/29090346/50ab20d2-4a6f-46d6-97b4-e5f139ba51d9)

**Comment by bazmetal** [comment]
Ok, I tried this. I ticked the box to bring up the game output, the game loaded without crash, and in the area I was having problems it did not crash either and I could walk around no problem. But then I noticed that nearly every image (online linked and on my hard drive) did not load. So I restarted the game, a few of them came back, but now I go to an area with lots of images and it crashes again ! Going back into the game and as it saved where I was, it crashes.

You say it could be a problem with the watermedia? I was using 1.3.20 and thought I would try and change to 1.3.22 and it still performed the crash. As you know if you do not load watermedia or the wrong version you get an error message on minecraft when it starts, it suggested that I use watermedia version 1.3.20 to 1.4. Looking on curseforge and as I use Minecraft 1.19.2 I cannot use any other versions than 1.3.20 and 1.3.22 to use.

So with the new option you got me to use to provide game output information, I have copied the last crash activity text, perhaps you can see what is going on through this please?

https://gist.github.com/bazmetal/1593f9ee0eb05eb6b064e4b786ffe252

**Comment by SrRapero720** [comment]
please paste more than the end, i just see vlc warnings, no usefull info

**Comment by SrRapero720** [comment]
new waterframes version uses more watermedia STUFF, rendering, fetching and patching... so i need to see what is causing it, i confirm is caused by native libraries (VLC or opengl) because crash cause is not stored on latest.log

**Comment by bazmetal** [comment]
For some weird reason it will not allow me to copy all of the text, strange. How you completely copy the text from this?

What is weirder is: I tried Water frames 1.4.0b Watermedia 1.3.22, loaded it from another area with nothing in it, then travelled to areas with lots of images and videos along with all other areas and they all worked flawlessly! I thought finally it was fixed just because of these versions put together, but unfortunately I exited with the game saving in the area with lots of images and videos, loaded it up, and it crashes again! I just don't believe it

**Comment by SrRapero720** [comment]
mmm, i can't copy all either.
try coping parts one by one adding it to gist.

**Comment by bazmetal** [comment]
Good grief, what a mission to copy the text bit by bit from game output!

Here is the text: https://gist.github.com/bazmetal/90bbd08cf935330dc2f21ab9e182633b

I hope this is clear for you, let me know if this is ok

**Comment by SrRapero720** [comment]
thanks you. ill do some attempts to fix

**Comment by bazmetal** [comment]
Ok thank you

**Comment by bazmetal** [comment]
Hi SrRapero,

Sorry I am not too knowledgeable on how things are done on github, I see there was a change made to watermedia 9 hours ago? Is the file still being made? Or is it done and has a link to download?

**Comment by SrRapero720** [comment]
issue as been solved, but curseforge mark watermedia as a virus
this is maybe because contains the entire VLC wrapped or some classes to do request to youtube and other web services.

until CF approves my mod you can download the GH release here https://github.com/SrRapero720/watermedia/releases/tag/1.3.23

EDIT:
You can also download from modrinth, but please, when CF release comes out download from here, modrinth doesn't give to me any incomes
https://modrinth.com/mod/watermedia/version/1.3.23

**Comment by bazmetal** [comment]
Hi SrRapero,

I tried downloading the 1.3.23 to use with waterframes 1.4.0b I tried both github and modrinth links just in case.

Unfortunately it is still presenting the same crash.

**Comment by bazmetal** [comment]
Is there nothing else that can be done to fix this?

**Comment by SrRapero720** [comment]
i need more details and logs doesn't give too much information
 i see you problem aren't crashes, are freezes, that means your game got freezed and you forced-close game

if issue was a deadlock then you need to do more advance things to discovering what is happening (because on my side deadlocks are fixed)

if you can then i teach you how to do that

**Comment by SrRapero720** [comment]
it doesn't matter, please downgrade to waterframes 1.3.x until i finish next version

**Comment by bazmetal** [comment]
Hi SrRapero

Yeah that's right it does force me to force close the game. But yah if it is my end perhaps you can show me how to do things with my end.

There is something I think I can do to tide me over, when I play the game I exit on a part that has little images and videos so that it launches without a crash because I can go through these areas with lots of images and videos, but loading from those heavy places crashes. So hopefully that will help until you do another version, or if you can like you say teach me how to look at advanced things my end.

I appreciate your efforts to help SrRapero, thanks :)

**Comment by bazmetal** [comment]
Actually trying it again it crashes when I travel those areas with lots of videos and images, so until you show me how to find out what the cause is or you release another version I will revert to 1.3.5

**Comment by bazmetal** [comment]
Hi SrRapero.

I've tried the latest Waterframes and Watermedia updates. The crashes no longer happen but it has the same problems as when first reported on Waterframes 1.3.1e & Watermedia 1.3.5 where video sounds play from a distance again. I was just wondering, is there a specific VLC version needed to get these videos running right?

**Comment by SrRapero720** [comment]
update watermedia, little mistake :/

**Comment by bazmetal** [comment]
Mistake?

**Comment by bazmetal** [comment]
Hi SrRapero,

So I tried the new watermedia 1.3.35 with waterframes 1.4.1a, it crashes when loading from a world with lots of images and worlds still BUT starting from a world with a low amount of images and videos and then travelling into a world with lots of images and videos in it does not crash! So it is usable if I finish and save the game in those areas! And what also has been solved is the distant sound from videos! Fantastic! The only new problem it has created since I put this new update in is that a neon block resource pack I have installed now makes glitchy weird colour flickering on the blocks.

But thanks very much for getting this mostly fixed it is awesome!

**Comment by bazmetal** [comment]
Hi SrRapero,

I'm sorry but there is another problem I have found in the new update, there are a lot of areas in my world that causes unplayable low fps. I thought it was because of there being too much in a new part of the world that I have just built so I tried water frames 1.3.1e and watermedia 1.3.5. and this version is running it flawlessly apart from the distant video sound bug.

**Comment by SrRapero720** [comment]
try with this version
https://www.curseforge.com/minecraft/mc-mods/waterframes/files/4904487

**Comment by SrRapero720** [comment]
assuming was fixed
