### ISSUE TITLE
Images and Videos client side settings?

### ISSUE THREAD

**Issue by Guitarsmasher** [SrRapero720/WATERFrAMES#19]
Hi do you plan on allowing users to disable rendering/caching images and or videos client sided so they don't have to render them upon joining a server?

I have people that I play with, whom don't have strong PCs and they can't really do anything since they're forced to render the images and videos. I don't mind if the mod is still required but I was hoping the other players could choose to opt in or not.

**Comment by SrRapero720** [comment]
It cannot be possible, basically you are requesting for disable the main feature of the mod.
I am working on a optimization on the major update (2.0)... for now i can give you few suggestions to reduce lag
1. Use lightweight images/videos
2. Decrease rendering distance
3. try to do not use more than 25 frames per chunk
