### ISSUE TITLE
Screen get blocked by JEI interface

### ISSUE THREAD

**Issue by SrRapero720** [SrRapero720/WATERFrAMES#2]
affects WATERFrAMES
caused by CreativeCore screen api.
https://github.com/CreativeMD/LittleFrames/issues/51

**Comment by CreativeMD** [comment]
Fixed in the newest CreativeCore version.

**Comment by SrRapero720** [comment]
yei

**Comment by SrRapero720** [comment]
or jei

**Comment by CreativeMD** [comment]
JEI.

**Comment by SrRapero720** [comment]
## ISSUE ADDRESSED, DOWNLOAD FIXED VERSION
- **CurseForge:** [1.18.2](https://www.curseforge.com/minecraft/mc-mods/waterframes/files/5305775) | [1.19.2](https://www.curseforge.com/minecraft/mc-mods/waterframes/files/5305778) | [1.20.1](https://www.curseforge.com/minecraft/mc-mods/waterframes/files/5305784)
