### ISSUE TITLE
``Feature Request`` 1.19.2 - 1.20.1/2 Add the ability to keep saved links in frame that is taken down using silk touch.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [SrRapero720/WATERFrAMES#20]
I had an epiphany ... what if instead of sending people sketchy youtube links the tutorial video is already in game? It would be a simple save function - have link assigned to placed frame. That way you could do something like paste a tutorial in game so people can study how to the thing they are trying to do without a need for anything external. I am a pack maker and I have a lot of large scale mods that no one wants to learn because then they have to take extra steps but if it was in the ftb quest book as a tutorial frame I could in theory stop being told where do I find X tutorial. this would also greatly save on writing :) Please please consider this.

Apologies I am dyslexic. I hope you understand the general thought process.

**Comment by SrRapero720** [comment]
Thats sounds like a feature that probably concerns to VideoPlayer and no WaterFrames.
You can copy blocks + NBT (including URL) using CTRL + Mouse wheel click.

but how i said... is not practical give to player a frame to place and watch a tutorial, something like a integrated button to play a fullscreen video is much better. as far i know... FTBQuest have a option to run commands. check it if works to you
https://www.curseforge.com/minecraft/mc-mods/video-player

**Comment by P3rf3ctXZer0** [comment]
You know that might work. Sorry I didn't realize that would be a good use case. Thanks for the first solution because that might work but it uses a version of watermedia that does not work with waterframes
