### ISSUE TITLE
1.20.1 Mod loading error has occurred

### ISSUE THREAD

**Issue by Cyranos** [SrRapero720/WATERFrAMES#22]
As per the title I can't get watermedia to load on 1.20.1

I have tried versions, 1.3.0 , 1.3.35 , 1.3.42 , 1.3.43 from curseforge & versions 1.3.42 & 1.3.43 from Modrinth but all of these cause the issue from what I've tried

Forge Version: 47.2.1
Creative Core Version: 2.11.5
Watermedia Version: 1.3.35
Waterframes Version: 1.3.1e

Crash Log; https://mclo.gs/XIAN5ec

**Comment by SrRapero720** [comment]
try with beta version
https://legacy.curseforge.com/minecraft/mc-mods/waterframes/files/4833018

Bug only occurs on waterframes 1.3.x

**Comment by Cyranos** [comment]
Yup can confirm that version has fixed the issue!
