### ISSUE TITLE
New 1.19.2 release

### ISSUE THREAD

**Issue by redditgold** [SrRapero720/WATERFrAMES#25]
Currently, the latest release for 1.19.2 is 4 months old, and predates a feature in available for other versions I'd really like that now seems to exist, which is the seek bar. It is important if for example you're watching a video with a group of people, and need to skip back due to somebody disconnecting.

The 1.18 and 1.20 branches seem to still be actively updated, so I would presume the latest code could be easily built for 1.19 too. If not, a backport if the seek feature would be more than enough for my use case too.

Thanks in advance.

**Comment by SrRapero720** [comment]
Waterframes Is currently on BETA. That means Is half unstable and has missing features.

I made a port current beta to 1.20.1 by votation on my discord (1.20.1 wins over 1.19.2). But Is just a ported versión, i am focusing on 1.18.2 to not waste time switching between versions. When i release the mod i'll port to all versíons (1.19.2, 1.20.1 and 1.16.5)
