### ISSUE TITLE
could not download image, 1.19.2

### ISSUE THREAD

**Issue by willy12345-www** [SrRapero720/WATERFrAMES#26]
Hello, I am playing on my server version 1.19.2
mod version 1.3.1 
wartermedia, 1.3.43
And one of the players received the error,"could not download image", and it doesn't load any video either, could someone help me solve it?

**Comment by SrRapero720** [comment]
I am focusing on waterframes beta 2.0. issue Is fixed on latest versión, but Is only available on 1.18.2. Will be fixed when i release oficial 1.19.2 port.

**Comment by SrRapero720** [comment]
can you try this version if was solved?
https://www.curseforge.com/minecraft/mc-mods/waterframes/files/4904487

**Comment by SrRapero720** [comment]
asumming was fixed
