### ISSUE TITLE
volume for videos not working?

### ISSUE THREAD

**Issue by amber-chong** [SrRapero720/WATERFrAMES#28]
hiya, so one of my players has an issue when there is a video playing, but no audio can be heard? and in the times where there is audio, its super quiet for them but really loud for everyone else around them.

theyve tried changing the game volumes and looking on the mod page for answers, but obviously cannot find any.

and its not just them, some other players have reported having the same issue ;-;;

any help would be appreciated, thanks !!

**Comment by SrRapero720** [comment]
can give me any media source or a video demostrationabout it? i can't reproduce it.
also, i need to know what OS, Arch, game version, mod version, api version (watermedia) and what other mods are involved

**Comment by amber-chong** [comment]
ill ask them to record a clip in a bit (theyre all sleeping or busy right now)
- the people that are experiencing the issues are on windows, but theres a couple of people with macOS
- some of them use tlauncher, others use regular but its 1.18.2 java
- mod version is 1.18.2 - 1.3.1d
- api version is 1.2.15
- modpack is this: https://www.curseforge.com/minecraft/modpacks/tortuguitas-smp

**Comment by SrRapero720** [comment]
welp, i dont need a clip for it, problem was you are using a old rusty watermedia version with a archived version of waterframes and broken version of videoplayer. even QSMP uses 2.0.0 beta. so my main suggestion was update to latest version

**Comment by amber-chong** [comment]
oh im a fool💀 thanks man 👍
