### ISSUE TITLE
could not download image

### ISSUE THREAD

**Issue by rayamiga** [SrRapero720/WATERFrAMES#3]
everytime i put a link directly from a youtube it says "could not download image" and i dont know what happened because it was working before

**Comment by SrRapero720** [comment]
Waterframes 1.2.0 uses a third-party server to support YouTube urls.
The problem Is the server Is down and waterframes can not lonher load youtube videos.

Right now Is fixed in dev using my new VLC dependency WATERMeDia.
Fixed version will be released on 1-2 weeks in the 2.0 version

**Comment by SrRapero720** [comment]
Fixed in 1.3.0a
https://www.curseforge.com/minecraft/mc-mods/waterframes
https://www.curseforge.com/minecraft/mc-mods/watermedia

REMEMBER UNINSTALL FancyVideo-API AND INSTALL WATERMeDIA (to make it works)
