### ISSUE TITLE
The game crashes when you click save

### ISSUE THREAD

**Issue by axe1esS** [SrRapero720/WATERFrAMES#31]
I put the link in, pressed the save button as it says in the guide, and the game freezes for a few seconds, and then crashes
After reading several pages on forums about the API used in waterframes, I tried to turn off the shaders, but the game still crashes if you click save.
Here are the crash logs
[crash-2023-12-26_17.02.46-server.txt](https://github.com/SrRapero720/waterframes/files/13772055/crash-2023-12-26_17.02.46-server.txt)

**Comment by SrRapero720** [comment]
update forge to latest version
