### ISSUE TITLE
Entities obscured by shaders

### ISSUE THREAD

**Issue by DankestO** [SrRapero720/WATERFrAMES#32]
basically the same bug:
https://github.com/SrRapero720/waterframes/issues/21#issue-1892848303

![Captura de pantalla 2023-12-31 130412](https://github.com/SrRapero720/waterframes/assets/126206944/f54b9b58-8047-4cf6-a88a-ce17b73a6063)
![Captura de pantalla 2023-12-31 130353](https://github.com/SrRapero720/waterframes/assets/126206944/6b10472e-bde4-4b5c-9675-6ed4c25a374a)

**Without shaders exactly the same thing happens, BUT at least I don't get dark xD**

![Captura de pantalla 2023-12-31 125747](https://github.com/SrRapero720/waterframes/assets/126206944/9e5e1ab5-28bb-4b65-88bd-48c469fe97ba)

Forge: 1.20.1 - 47.2.0
Waterframe: 1.20.1/2.0.0-beta5.1
embeddium: 1.20.1 - 0.2.16
oculus: 1.20.1 - 1.6.9
Shaders: complementary-reimagined [r5.1.1]

**Comment by SrRapero720** [comment]
not again :(

**Comment by SrRapero720** [comment]
I can't solve this issue, i dont know why is happening on new versions but in old versions works pretty fine.
Please report this bug to SecurityCrafft to almost attempt to fix this.

Also affects other tile entities and hand rendering... again, no idea, use other shader do nothing.

**Comment by DankestO** [comment]
As far as I know they changed a couple of things in a certain version, but a few weeks ago in 0.3.0 Embeddium changed things again: https://github.com/embeddedt/embeddium/wiki/Changelog#030
So the mods that have some kind of compatibility with it will have to make them compatible with Embeddium again, I'm not sure if those changes can help you in some way.

Why Securitycraft? I mean, it is the frame area that turns the entities black 🤔

**Comment by BrangGit** [comment]
You can downgrade to these versions as a workaround :

    CreativeCore 2.11.10
    WaterFrames 2.0.0-beta2.1
    WaterMedia 2.0.10

Unfortunately, this WaterFrames version doesn't support latest CreativeCore updates (>= 2.11.20) and lead to crashes when interacting with frames. 
The project i'm working on requires CreativeCore >= 2.11.20 for PlayerRevive stability, so i'll go with the lighting bug for now, hoping you'll find help and/or a solution :)

**Comment by SrRapero720** [comment]
## ISSUE ADDRESSED, DOWNLOAD FIXED VERSION
- **CurseForge:** [1.18.2](https://www.curseforge.com/minecraft/mc-mods/waterframes/files/5305775) | [1.19.2](https://www.curseforge.com/minecraft/mc-mods/waterframes/files/5305778) | [1.20.1](https://www.curseforge.com/minecraft/mc-mods/waterframes/files/5305784)

**Comment by DankestO** [comment]
I'm sorry to be the one to say it but...
The bug persists :(

Certainly you are never going to set the brightness to the minimum in the game, but even when you lower the brightness to 25% you can already notice that entities around you get a little darker while the television is still in your range of vision.
