### ISSUE TITLE
Incompatibility and error when trying to install on 1.20.1

### ISSUE THREAD

**Issue by YuriAlessandro** [SrRapero720/WATERFrAMES#33]
When I install from CurseForge on Minecraft 1.20.1, Forge Version 47.2.20, it shows that the WaterMedia version (2.0.25) is incompatible:

![image](https://github.com/SrRapero720/waterframes/assets/14967048/57c909c3-c144-41b5-a1c6-580fd47b74bc)

CurseForge at least shows me those versions for WaterMedia:

![image](https://github.com/SrRapero720/waterframes/assets/14967048/b75a08c8-61f2-4f57-aa35-a46986b5db0b)

If I install either watermedia-1.3.43 or watermedia-1.3.0 (options between 1.3 or 1.4), I get the following error:

![image](https://github.com/SrRapero720/waterframes/assets/14967048/e5f16e6d-7e0c-4767-8a5d-2af7d88f4d0f)

As you can see I'm also trying to use Video Player mod.

Is there any way to fix this?

**Comment by SrRapero720** [comment]
you checked versions for watermedia... did you check versions for waterframes? 👀

**Comment by YuriAlessandro** [comment]
@SrRapero720 WaterFrames only have 2 versions available, and only one is release

![image](https://github.com/SrRapero720/waterframes/assets/14967048/e96fef29-f08a-4594-99b8-ca6ff20dca84)

**Comment by SrRapero720** [comment]
try use 2.0.0-beta5.1

**Comment by YuriAlessandro** [comment]
Yeah man it worked, thanks very much for the quick response.
