### ISSUE TITLE
doesn't work with all shaders BUG

### ISSUE THREAD

**Issue by Edzeron** [SrRapero720/WATERFrAMES#35]
hello, when I activate the shaders the display does not work, changing the frame parameters does not change anything, I would like to know if there was a way to resolve the problem.

reference

waterframes-1.19.2-1.3.1e
watermedia-1.3.43
CreativeCore_FORGE_v2.9.4_mc1.19.2

![2024-02-22_02 51 25](https://github.com/SrRapero720/waterframes/assets/31419025/b49a1132-aac6-4e26-8927-05f41f08e315)

![2024-02-22_02 51 55](https://github.com/SrRapero720/waterframes/assets/31419025/661c47d3-59f1-4dc5-b05f-d50006e150cd)

**Comment by SrRapero720** [comment]
you're using an old WF version
use WATERFrAMES 2.0.0-beta5 with WATERMeDIA 2.0.x
