### ISSUE TITLE
Crash on clicking save in projector

### ISSUE THREAD

**Issue by Enderteck** [SrRapero720/WATERFrAMES#36]
Here are the logs for a crash on Minecraft 1.20.1 

Latest version of NeoForge (41.1.100).

Fedora 39 Workstation edition on Wayland.
RTX 3060 mobile w/ latest Nvidia drivers.
Intel core i5 11th gen.

I pasted a youtube url and when I pressed save, some glitchy audio (very low and not all the time) started playing and it paused my video playing on another monitor (or at least muted it). Then the window was unresponsive. It then crashed.
The game was heavily modded tho so I hope this is not due to another mod.

Log:

[NeoForge 1.20.1 Server Log](https://mclo.gs/Nv1bhWw)

Crash report:
 
[NeoForge 1.20.1 Crash Report](https://mclo.gs/wReeaPQ)

fml file found in the crash reports folder:

[Vanilla 1.20.1 Crash Report](https://mclo.gs/v4oO8gv)

Mod list:

YungsBetterDungeons-1.20-Forge-4.0.3.jar          |YUNG's Better Dungeons        |betterdungeons                |1.20-Forge-4.0.3    |COMMON_SET|Manifest: NOSIGNATURE
		create_misc_and_things_ 1.20.1_4.0A.jar           |create: things and misc       |create_things_and_misc        |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		YungsBetterWitchHuts-1.20-Forge-3.0.3.jar         |YUNG's Better Witch Huts      |betterwitchhuts               |1.20-Forge-3.0.3    |COMMON_SET|Manifest: NOSIGNATURE
		geckolib-neoforge-1.20.1-4.4.jar                  |GeckoLib 4                    |geckolib                      |4.4                 |COMMON_SET|Manifest: NOSIGNATURE
		player-animation-lib-forge-1.0.2-rc1+1.20.jar     |Player Animator               |playeranimator                |1.0.2-rc1+1.20      |COMMON_SET|Manifest: NOSIGNATURE
		botarium-forge-1.20.1-2.3.1.jar                   |Botarium                      |botarium                      |2.3.1               |COMMON_SET|Manifest: NOSIGNATURE
		YungsBetterOceanMonuments-1.20-Forge-3.0.4.jar    |YUNG's Better Ocean Monuments |betteroceanmonuments          |1.20-Forge-3.0.4    |COMMON_SET|Manifest: NOSIGNATURE
		sophisticatedcore-1.20.1-0.5.113.524.jar          |Sophisticated Core            |sophisticatedcore             |0.5.113.524         |COMMON_SET|Manifest: NOSIGNATURE
		EggDelight-v1.1-1.20.1.jar                        |Egg Delight                   |eggdelight                    |1.1                 |COMMON_SET|Manifest: NOSIGNATURE
		Controlling-forge-1.20.1-12.0.2.jar               |Controlling                   |controlling                   |12.0.2              |COMMON_SET|Manifest: NOSIGNATURE
		citadel-2.4.9-1.20.1.jar                          |Citadel                       |citadel                       |2.4.9               |ERROR     |Manifest: NOSIGNATURE
		alexsmobs-1.22.7.jar                              |Alex's Mobs                   |alexsmobs                     |1.22.7              |COMMON_SET|Manifest: NOSIGNATURE
		YungsApi-1.20-Forge-4.0.2.jar                     |YUNG's API                    |yungsapi                      |1.20-Forge-4.0.2    |COMMON_SET|Manifest: NOSIGNATURE
		Powah-5.0.4.jar                                   |Powah                         |powah                         |5.0.4               |ERROR     |Manifest: NOSIGNATURE
		mixinextras-forge-0.3.2.jar                       |MixinExtras                   |mixinextras                   |0.3.2               |COMMON_SET|Manifest: NOSIGNATURE
		Bookshelf-Forge-1.20.1-20.1.8.jar                 |Bookshelf                     |bookshelf                     |20.1.8              |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		sophisticatedbackpacks-1.20.1-3.19.5.988.jar      |Sophisticated Backpacks       |sophisticatedbackpacks        |3.19.5.988          |COMMON_SET|Manifest: NOSIGNATURE
		littlecontraptions-forge-1.20.1.2.jar             |Little Contraptions           |littlecontraptions            |1.20.1.2            |COMMON_SET|Manifest: NOSIGNATURE
		create_dragon_lib-1.20.1-1.3.3.jar                |Create: Dragon Lib            |create_dragon_lib             |1.3.3               |COMMON_SET|Manifest: NOSIGNATURE
		createdieselgenerators-1.20.1-1.2f.jar            |Create Diesel Generators      |createdieselgenerators        |1.20.1-1.2f         |COMMON_SET|Manifest: NOSIGNATURE
		balm-forge-1.20.1-7.2.1.jar                       |Balm                          |balm                          |7.2.1               |COMMON_SET|Manifest: NOSIGNATURE
		carryon-forge-1.20.1-2.1.2.7.jar                  |Carry On                      |carryon                       |2.1.2.7             |ERROR     |Manifest: NOSIGNATURE
		interiors-0.5.2+mc1.20.1-FORGE.jar                |Create: Interiors             |interiors                     |0.5.2               |COMMON_SET|Manifest: NOSIGNATURE
		YungsBetterNetherFortresses-1.20-Forge-2.0.5.jar  |YUNG's Better Nether Fortresse|betterfortresses              |1.20-Forge-2.0.5    |COMMON_SET|Manifest: NOSIGNATURE
		cloth-config-11.1.118-forge.jar                   |Cloth Config v10 API          |cloth_config                  |11.1.118            |COMMON_SET|Manifest: NOSIGNATURE
		shetiphiancore-forge-1.20.1-1.2.jar               |ShetiPhian-Core               |shetiphiancore                |1.20.1-1.2          |COMMON_SET|Manifest: NOSIGNATURE
		supplementaries-1.20-2.7.21.jar                   |Supplementaries               |supplementaries               |1.20-2.7.21         |COMMON_SET|Manifest: NOSIGNATURE
		embeddium-0.2.16+mc1.20.1.jar                     |Embeddium                     |embeddium                     |0.2.16+mc1.20.1     |COMMON_SET|Manifest: NOSIGNATURE
		athena-forge-1.20.1-3.1.1.jar                     |Athena                        |athena                        |3.1.1               |COMMON_SET|Manifest: NOSIGNATURE
		corpse-forge-1.20.1-1.0.10.jar                    |Corpse                        |corpse                        |1.20.1-1.0.10       |COMMON_SET|Manifest: NOSIGNATURE
		chipped-forge-1.20.1-3.0.1.jar                    |Chipped                       |chipped                       |3.0.1               |COMMON_SET|Manifest: NOSIGNATURE
		FarmersDelight-1.20.1-1.2.3.jar                   |Farmer's Delight              |farmersdelight                |1.20.1-1.2.3        |COMMON_SET|Manifest: NOSIGNATURE
		RapidLeafDecay-1.20.1-2.0.2.jar                   |Rapid Leaf Decay              |rapid_leaf_decay              |2.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		ironfurnaces-1.20.1-4.1.3.jar                     |Iron Furnaces                 |ironfurnaces                  |4.1.3               |COMMON_SET|Manifest: NOSIGNATURE
		mcw-fences-1.0.7-mc1.20.1forge.jar                |Macaw's Fences and Walls      |mcwfences                     |1.0.7               |COMMON_SET|Manifest: NOSIGNATURE
		YungsBridges-1.20-Forge-4.0.3.jar                 |YUNG's Bridges                |yungsbridges                  |1.20-Forge-4.0.3    |COMMON_SET|Manifest: NOSIGNATURE
		resourcefulconfig-forge-1.20.1-2.1.2.jar          |Resourcefulconfig             |resourcefulconfig             |2.1.2               |COMMON_SET|Manifest: NOSIGNATURE
		AdditionalPlacements-1.20-1.7.6.jar               |Additional Placements         |additionalplacements          |1.7.6               |ERROR     |Manifest: NOSIGNATURE
		modelfix-1.14.jar                                 |Model Gap Fix                 |modelfix                      |1.14                |COMMON_SET|Manifest: NOSIGNATURE
		curios-forge-5.4.7+1.20.1.jar                     |Curios API                    |curios                        |5.4.7+1.20.1        |COMMON_SET|Manifest: NOSIGNATURE
		suppsquared-1.20-1.1.12.jar                       |Supplementaries Squared       |suppsquared                   |1.20-1.1.12         |COMMON_SET|Manifest: NOSIGNATURE
		oculus-mc1.20.1-1.6.13.jar                        |Oculus                        |oculus                        |1.6.13              |COMMON_SET|Manifest: NOSIGNATURE
		collective-1.20.1-7.30.jar                        |Collective                    |collective                    |7.30                |COMMON_SET|Manifest: NOSIGNATURE
		camera-forge-1.20.1-1.0.8.jar                     |Camera Mod                    |camera                        |1.20.1-1.0.8        |COMMON_SET|Manifest: NOSIGNATURE
		Searchables-forge-1.20.1-1.0.2.jar                |Searchables                   |searchables                   |1.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		elevatorid-1.20.1-1.9.1.jar                       |Elevator Mod                  |elevatorid                    |1.20.1-1.9          |COMMON_SET|Manifest: NOSIGNATURE
		ThirstWasTaken-1.20.1-1.3.5.jar                   |Thirst Was Taken              |thirst                        |1.3.5               |COMMON_SET|Manifest: NOSIGNATURE
		ftb-ultimine-forge-2001.1.4.jar                   |FTB Ultimine                  |ftbultimine                   |2001.1.4            |ERROR     |Manifest: NOSIGNATURE
		YungsBetterStrongholds-1.20-Forge-4.0.3.jar       |YUNG's Better Strongholds     |betterstrongholds             |1.20-Forge-4.0.3    |COMMON_SET|Manifest: NOSIGNATURE
		YungsMenuTweaks-1.20.1-Forge-1.0.1.jar            |YUNG's Menu Tweaks            |yungsmenutweaks               |1.20.1-Forge-1.0.1  |COMMON_SET|Manifest: NOSIGNATURE
		resourcefullib-forge-1.20.1-2.1.20.jar            |Resourceful Lib               |resourcefullib                |2.1.20              |ERROR     |Manifest: NOSIGNATURE
		littlelogistics-mc1.20.1-v1.20.1.2.jar            |Little Logistics              |littlelogistics               |1.20.1.2            |ERROR     |Manifest: NOSIGNATURE
		cfm-forge-1.20.1-7.0.0-pre36.jar                  |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre36         |ERROR     |Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		architectury-9.1.12-forge.jar                     |Architectury                  |architectury                  |9.1.12              |COMMON_SET|Manifest: NOSIGNATURE
		mcw-furniture-3.2.1-mc1.20.1forge.jar             |Macaw's Furniture             |mcwfurnitures                 |3.2.1               |COMMON_SET|Manifest: NOSIGNATURE
		ItemPhysic_FORGE_v1.7.0_mc1.20.1.jar              |ItemPhysic                    |itemphysic                    |1.7.0               |COMMON_SET|Manifest: NOSIGNATURE
		YungsBetterEndIsland-1.20-Forge-2.0.4.jar         |YUNG's Better End Island      |betterendisland               |1.20-Forge-2.0.4    |COMMON_SET|Manifest: NOSIGNATURE
		rubidium-extra-0.5.3.1+mc1.20.1-build.110.jar     |Rubidium/Embeddium Extra      |rubidium_extra                |0.5.3.1+mc1.20.1-bui|COMMON_SET|Manifest: NOSIGNATURE
		crafting+-1.1.jar                                 |Crafting+                     |mr_crafting                   |1.1                 |COMMON_SET|Manifest: NOSIGNATURE
		JadeAddons-1.20.1-forge-5.2.2.jar                 |Jade Addons                   |jadeaddons                    |5.2.2               |COMMON_SET|Manifest: NOSIGNATURE
		framework-forge-1.20.1-0.6.16.jar                 |Framework                     |framework                     |0.6.16              |COMMON_SET|Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		YungsBetterMineshafts-1.20-Forge-4.0.4.jar        |YUNG's Better Mineshafts      |bettermineshafts              |1.20-Forge-4.0.4    |COMMON_SET|Manifest: NOSIGNATURE
		sliceanddice-forge-3.2.0.jar                      |Create Slice & Dice           |sliceanddice                  |3.2.0               |COMMON_SET|Manifest: NOSIGNATURE
		sixstairs-1.20.1-11-forge.jar                     |SixStairs                     |sixstairs                     |1.20.1-11-forge     |COMMON_SET|Manifest: NOSIGNATURE
		Essential (forge_1.20.1).jar                      |Essential                     |essential                     |1.3.0.2+ge922acc4a7 |COMMON_SET|Manifest: NOSIGNATURE
		YungsBetterJungleTemples-1.20-Forge-2.0.4.jar     |YUNG's Better Jungle Temples  |betterjungletemples           |1.20-Forge-2.0.4    |COMMON_SET|Manifest: NOSIGNATURE
		BetterAdvancements-1.20.1-0.3.2.162.jar           |Better Advancements           |betteradvancements            |0.3.2.162           |COMMON_SET|Manifest: NOSIGNATURE
		inventorysorter-1.20.1-23.0.1.jar                 |Simple Inventory Sorter       |inventorysorter               |23.0.1              |COMMON_SET|Manifest: NOSIGNATURE
		BetterAnimationsCollection-v8.0.0-1.20.1-Forge.jar|Better Animations Collection  |betteranimationscollection    |8.0.0               |COMMON_SET|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		bellsandwhistles-0.4.3-1.20.x.jar                 |Create: Bells & Whistles      |bellsandwhistles              |0.4.3-1.20.x        |COMMON_SET|Manifest: NOSIGNATURE
		Cucumber-1.20.1-7.0.7.jar                         |Cucumber Library              |cucumber                      |7.0.7               |COMMON_SET|Manifest: NOSIGNATURE
		ftb-library-forge-2001.1.4.jar                    |FTB Library                   |ftblibrary                    |2001.1.4            |COMMON_SET|Manifest: NOSIGNATURE
		watermedia-2.0.25.jar                             |WaterMedia                    |watermedia                    |2.0.25              |COMMON_SET|Manifest: NOSIGNATURE
		harvestwithease-1.20.1-8.0.0.2-forge.jar          |Harvest with ease             |harvestwithease               |8.0.0.2             |COMMON_SET|Manifest: NOSIGNATURE
		sophisticatedstorage-1.20.1-0.8.65.680.jar        |Sophisticated Storage         |sophisticatedstorage          |0.8.65.680          |COMMON_SET|Manifest: NOSIGNATURE
		tia-1.20-1.1-forge.jar                            |Tiny Item Animations          |tia                           |1.20-1.1            |COMMON_SET|Manifest: NOSIGNATURE
		jei-1.20.1-forge-15.2.0.27.jar                    |Just Enough Items             |jei                           |15.2.0.27           |COMMON_SET|Manifest: NOSIGNATURE
		Mekanism-1.20.1-10.4.5.19.jar                     |Mekanism                      |mekanism                      |10.4.5              |COMMON_SET|Manifest: NOSIGNATURE
		MekanismGenerators-1.20.1-10.4.5.19.jar           |Mekanism: Generators          |mekanismgenerators            |10.4.5              |COMMON_SET|Manifest: NOSIGNATURE
		MekanismAdditions-1.20.1-10.4.5.19.jar            |Mekanism: Additions           |mekanismadditions             |10.4.5              |COMMON_SET|Manifest: NOSIGNATURE
		MekanismTools-1.20.1-10.4.5.19.jar                |Mekanism: Tools               |mekanismtools                 |10.4.5              |COMMON_SET|Manifest: NOSIGNATURE
		Paxi-1.20-Forge-4.0.jar                           |Paxi                          |paxi                          |1.20-Forge-4.0      |COMMON_SET|Manifest: NOSIGNATURE
		goldenhopper-forge-1.20.1-1.4.1.jar               |Golden Hopper                 |goldenhopper                  |1.4.1               |COMMON_SET|Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		comforts-forge-6.3.4+1.20.1.jar                   |Comforts                      |comforts                      |6.3.4+1.20.1        |COMMON_SET|Manifest: NOSIGNATURE
		pneumaticcraft-repressurized-6.0.13+mc1.20.1.jar  |PneumaticCraft: Repressurized |pneumaticcraft                |6.0.13+mc1.20.1     |ERROR     |Manifest: NOSIGNATURE
		mighty_mail-forge-1.20.1-1.0.14.jar               |Mighty Mail                   |mighty_mail                   |1.0.14              |COMMON_SET|Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		everycomp-1.20-2.6.23.jar                         |Every Compat                  |everycomp                     |1.20-2.6.23         |COMMON_SET|Manifest: NOSIGNATURE
		YungsBetterDesertTemples-1.20-Forge-3.0.3.jar     |YUNG's Better Desert Temples  |betterdeserttemples           |1.20-Forge-3.0.3    |COMMON_SET|Manifest: NOSIGNATURE
		catalogue-forge-1.20.1-1.8.0.jar                  |Catalogue                     |catalogue                     |1.8.0               |COMMON_SET|Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		Terralith_1.20.4_v2.4.11.jar                      |Terralith                     |terralith                     |2.4.11              |COMMON_SET|Manifest: NOSIGNATURE
		puzzlesaccessapi-forge-8.0.7.jar                  |Puzzles Access Api            |puzzlesaccessapi              |8.0.7               |COMMON_SET|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		forge-1.20.1-47.2.19-universal.jar                |Forge                         |forge                         |47.2.19             |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		extractinator-forge-1.20.1-2.3.0.jar              |Extractinator                 |extractinator                 |2.3.0               |COMMON_SET|Manifest: NOSIGNATURE
		mcw-paths-1.0.3forge-mc1.20.1.jar                 |Macaw's Paths and Pavings     |mcwpaths                      |1.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		emotecraft-for-MC1.20.1-2.2.7-b.build.50-forge.jar|Emotecraft                    |emotecraft                    |2.2.7-b.build.50    |COMMON_SET|Manifest: NOSIGNATURE
		craftingtweaks-forge-1.20-18.2.2.jar              |CraftingTweaks                |craftingtweaks                |18.2.2              |COMMON_SET|Manifest: NOSIGNATURE
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		cofh_core-1.20.1-11.0.0.51.jar                    |CoFH Core                     |cofh_core                     |11.0.0              |ERROR     |Manifest: NOSIGNATURE
		thermal_core-1.20.1-11.0.2.18.jar                 |Thermal Series                |thermal                       |11.0.2              |ERROR     |Manifest: NOSIGNATURE
		thermal_integration-1.20.1-11.0.0.23.jar          |Thermal Integration           |thermal_integration           |11.0.0              |COMMON_SET|Manifest: NOSIGNATURE
		thermal_innovation-1.20.1-11.0.0.21.jar           |Thermal Innovation            |thermal_innovation            |11.0.0              |COMMON_SET|Manifest: NOSIGNATURE
		thermal_foundation-1.20.1-11.0.2.64.jar           |Thermal Foundation            |thermal_foundation            |11.0.2              |COMMON_SET|Manifest: NOSIGNATURE
		thermal_expansion-1.20.1-11.0.0.27.jar            |Thermal Expansion             |thermal_expansion             |11.0.0              |COMMON_SET|Manifest: NOSIGNATURE
		thermal_locomotion-1.20.1-11.0.0.17.jar           |Thermal Locomotion            |thermal_locomotion            |11.0.0              |COMMON_SET|Manifest: NOSIGNATURE
		thermal_dynamics-1.20.1-11.0.0.21.jar             |Thermal Dynamics              |thermal_dynamics              |11.0.0              |COMMON_SET|Manifest: NOSIGNATURE
		alexscaves-1.0.9.jar                              |Alex's Caves                  |alexscaves                    |1.0.9               |COMMON_SET|Manifest: NOSIGNATURE
		voicechat-forge-1.20.1-2.4.32.jar                 |Simple Voice Chat             |voicechat                     |1.20.1-2.4.32       |COMMON_SET|Manifest: NOSIGNATURE
		sound-physics-remastered-forge-1.20.1-1.3.1.jar   |Sound Physics Remastered      |sound_physics_remastered      |1.20.1-1.3.1        |COMMON_SET|Manifest: NOSIGNATURE
		Steam_Rails-1.5.3+forge-mc1.20.1.jar              |Create: Steam 'n' Rails       |railways                      |1.5.3+forge-mc1.20.1|COMMON_SET|Manifest: NOSIGNATURE
		EnchantmentDescriptions-Forge-1.20.1-17.0.13.jar  |EnchantmentDescriptions       |enchdesc                      |17.0.13             |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		TerraBlender-forge-1.20.1-3.0.1.2.jar             |TerraBlender                  |terrablender                  |3.0.1.2             |COMMON_SET|Manifest: NOSIGNATURE
		BiomesOPlenty-1.20.1-18.0.0.598.jar               |Biomes O' Plenty              |biomesoplenty                 |18.0.0.598          |COMMON_SET|Manifest: NOSIGNATURE
		sebastrnlib-4.0.0.jar                             |Sebastrn Lib                  |sebastrnlib                   |4.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		Patchouli-1.20.1-84-FORGE.jar                     |Patchouli                     |patchouli                     |1.20.1-84-FORGE     |COMMON_SET|Manifest: NOSIGNATURE
		refinedcooking-4.0.0.jar                          |Refined Cooking               |refinedcooking                |4.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		cookingforblockheads-forge-1.20-16.0.1.jar        |CookingForBlockheads          |cookingforblockheads          |16.0.1              |COMMON_SET|Manifest: NOSIGNATURE
		refinedstorage-1.12.4.jar                         |Refined Storage               |refinedstorage                |1.12.4              |COMMON_SET|Manifest: NOSIGNATURE
		moonlight-1.20-2.8.82-forge.jar                   |Moonlight Library             |moonlight                     |1.20-2.8.82         |COMMON_SET|Manifest: NOSIGNATURE
		MouseTweaks-forge-mc1.20-2.25.jar                 |Mouse Tweaks                  |mousetweaks                   |2.25                |COMMON_SET|Manifest: NOSIGNATURE
		ForgeConfigScreens-v8.0.2-1.20.1-Forge.jar        |Forge Config Screens          |forgeconfigscreens            |8.0.2               |COMMON_SET|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		mysterious_mountain_lib-1.4.2-1.20.1.jar          |Mysterious Mountain Lib       |mysterious_mountain_lib       |1.4.2-1.20.1        |COMMON_SET|Manifest: NOSIGNATURE
		corn_delight-1.0.3-1.20.1.jar                     |Corn Delight                  |corn_delight                  |1.0.3-1.20.1        |COMMON_SET|Manifest: NOSIGNATURE
		ImmersiveEngineering-1.20.1-10.0.0-169.jar        |Immersive Engineering         |immersiveengineering          |1.20.1-10.0.0-169   |ERROR     |Manifest: 44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		mixinsquared-forge-0.1.1.jar                      |MixinSquared                  |mixinsquared                  |0.1.1               |COMMON_SET|Manifest: NOSIGNATURE
		Jade-1.20.1-forge-11.7.1.jar                      |Jade                          |jade                          |11.7.1              |COMMON_SET|Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.11.18_mc1.20.1.jar          |CreativeCore                  |creativecore                  |2.11.18             |COMMON_SET|Manifest: NOSIGNATURE
		waterframes-1.20.1-2.0.0-beta5.1.jar              |WaterFrames                   |waterframes                   |2.0.0-beta5.1       |COMMON_SET|Manifest: NOSIGNATURE
		createutilities-0.1.4+1.20.1.jar                  |Create Utilities              |createutilities               |0.1.4+1.20.1        |COMMON_SET|Manifest: NOSIGNATURE
		spectrelib-forge-0.13.14+1.20.1.jar               |SpectreLib                    |spectrelib                    |0.13.14+1.20.1      |COMMON_SET|Manifest: NOSIGNATURE
		inventorio-1.20-forge-1.9.2.jar                   |Inventorio                    |inventorio                    |1.9.2               |COMMON_SET|Manifest: NOSIGNATURE
		Ding-1.20.1-Forge-1.4.1.jar                       |Ding                          |ding                          |1.4.1               |COMMON_SET|Manifest: NOSIGNATURE
		createendertransmission-2.0.6-1.20.1.jar          |Create Ender Transmission     |createendertransmission       |2.0.6-1.20.1        |COMMON_SET|Manifest: NOSIGNATURE
		garnished-1.5.1-hotfix-1+1.20.1.jar               |Create: Garnished             |garnished                     |1.5.1-hotfix-1+1.20.|COMMON_SET|Manifest: NOSIGNATURE
		EnderIO-1.20.1-6.0.23-alpha.jar                   |Ender IO                      |enderio                       |6.0.23-alpha        |ERROR     |Manifest: NOSIGNATURE
		kffmod-4.10.0.jar                                 |Kotlin For Forge              |kotlinforforge                |4.10.0              |COMMON_SET|Manifest: NOSIGNATURE
		notenoughanimations-forge-1.7.0-mc1.20.1.jar      |NotEnoughAnimations           |notenoughanimations           |1.7.0               |COMMON_SET|Manifest: NOSIGNATURE
		flywheel-forge-1.20.1-0.6.10-7.jar                |Flywheel                      |flywheel                      |0.6.10-7            |ERROR     |Manifest: NOSIGNATURE
		compressedcreativity-1.20.1-0.1.8.b.jar           |Compressed Creativity         |compressedcreativity          |1.20.1-0.1.8.b      |COMMON_SET|Manifest: NOSIGNATURE
		create-1.20.1-0.5.1.f.jar                         |Create                        |create                        |0.5.1.f             |ERROR     |Manifest: NOSIGNATURE
		create-structures-0.1.1-1.20.1-FORGE.jar          |Create: Structures            |create_structures             |0.1.1               |COMMON_SET|Manifest: NOSIGNATURE
		create-stuff-additions1.20.1_v2.0.4a.jar          |Create Stuff & Additions      |create_sa                     |2.0.4.              |COMMON_SET|Manifest: NOSIGNATURE
		thermal_cultivation-1.20.1-11.0.0.22.jar          |Thermal Cultivation           |thermal_cultivation           |11.0.0              |COMMON_SET|Manifest: NOSIGNATURE
		polymorph-forge-0.49.2+1.20.1.jar                 |Polymorph                     |polymorph                     |0.49.2+1.20.1       |COMMON_SET|Manifest: NOSIGNATURE
		storagedrawers-1.20.1-12.0.2.jar                  |Storage Drawers               |storagedrawers                |12.0.2              |COMMON_SET|Manifest: NOSIGNATURE
		entityculling-forge-1.6.2-mc1.20.1.jar            |EntityCulling                 |entityculling                 |1.6.2               |COMMON_SET|Manifest: NOSIGNATURE
		appleskin-forge-mc1.20.1-2.5.1.jar                |AppleSkin                     |appleskin                     |2.5.1+mc1.20.1      |COMMON_SET|Manifest: NOSIGNATURE
		ferritecore-6.0.1-forge.jar                       |Ferrite Core                  |ferritecore                   |6.0.1               |COMMON_SET|Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		visuality-forge-2.0.2.jar                         |Visuality: Reforged           |visuality                     |2.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		PuzzlesLib-v8.1.13-1.20.1-Forge.jar               |Puzzles Lib                   |puzzleslib                    |8.1.13              |COMMON_SET|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		create-track-map-1.4+mc1.20.1-neoforge.jar        |Create Track Map              |createtrackmap                |1.4                 |COMMON_SET|Manifest: NOSIGNATURE
		BetterF3-7.0.2-Forge-1.20.1.jar                   |BetterF3                      |betterf3                      |7.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		refinedstorageaddons-0.10.0.jar                   |Refined Storage Addons        |refinedstorageaddons          |0.10.0              |COMMON_SET|Manifest: NOSIGNATURE
		textrues_embeddium_options-0.1.3+mc1.20.1.jar     |TexTrue's Embeddium Options   |textrues_embeddium_options    |0.1.3+mc1.20.1      |COMMON_SET|Manifest: NOSIGNATURE
		create_enchantment_industry-1.20.1-for-create-0.5.|Create Enchantment Industry   |create_enchantment_industry   |1.2.7.h             |COMMON_SET|Manifest: NOSIGNATURE
		createaddition-1.20.1-1.1.1.jar                   |Create Crafts & Additions     |createaddition                |1.20.1-1.1.1        |COMMON_SET|Manifest: NOSIGNATURE
		ad_astra-forge-1.20.1-1.15.7.jar                  |Ad Astra                      |ad_astra                      |1.15.7              |ERROR     |Manifest: NOSIGNATURE

**Comment by SrRapero720** [comment]
i like how the crash report had nothing related to crash in logs amd the FML crash report

**PLEASE**, clear all your logs and crash reports and re-run again.... nothing is related to waterframes/watermedia and nothing is related to nothing

**Comment by Enderteck** [comment]
Damn sorry. Mb will try to read more of the logs

**Comment by Enderteck** [comment]
The issue was resolved after coming back to the world multiple times. Very weird
