### ISSUE TITLE
Cant see videos?

### ISSUE THREAD

**Issue by marsupialgoddess** [SrRapero720/WATERFrAMES#39]
Whenever I am both on a singleplayer or multiplayer world, modded. The TV screen just shows up as black? I can hear the audio, and see the loading screen but the video itself is black? The version is 1.18.2, and the version of waterframes is 1.18.2-2.0.0-beta5

**Comment by SrRapero720** [comment]
## ISSUE ADDRESSED, DOWNLOAD FIXED VERSION
- **CurseForge:** [1.18.2](https://www.curseforge.com/minecraft/mc-mods/waterframes/files/5305775) | [1.19.2](https://www.curseforge.com/minecraft/mc-mods/waterframes/files/5305778) | [1.20.1](https://www.curseforge.com/minecraft/mc-mods/waterframes/files/5305784)

**Comment by Kurizek27** [comment]
im on 1.21.1 and it happened to me. can someone tell me every library this mod needs? (im on arch linux so im pretty sure im missing something because its working on ubuntu)
