### ISSUE TITLE
Assertion failed!

### ISSUE THREAD

**Issue by jv20064** [SrRapero720/WATERFrAMES#4]
![5a11bee7-f43b-4dc3-a7f9-f720b582044b](https://github.com/SrRapero720/waterframes/assets/136287570/9af978db-3aa0-44e1-80a9-bcec7c92d539)

**Comment by SrRapero720** [comment]
This issue is caused by FancyVideo-API. I would suggest that you report it to the creator but I am already working with a better library made by me, which will be used in version 2.0 of the mod.

it's already solved (in dev)

**Comment by SrRapero720** [comment]
Fixed in 1.3.0a
https://www.curseforge.com/minecraft/mc-mods/waterframes
https://www.curseforge.com/minecraft/mc-mods/watermedia

REMEMBER UNINSTALL FancyVideo-API AND INSTALL WATERMeDIA (to make it works)
