### ISSUE TITLE
youtube doesn't work 1.19.2 2.0.31

### ISSUE THREAD

**Issue by ProGoofster** [SrRapero720/WATERFrAMES#42]
![2024-04-13_20 11 30](https://github.com/SrRapero720/watermedia/assets/59934842/5b2f8cda-8d6e-43e9-888f-74710bffeb2b)

**Comment by SrRapero720** [comment]
downgrading watermedia changes something? to the 2.0.26 for exaMPLE

**Comment by SrRapero720** [comment]
## ISSUE ADDRESSED, DOWNLOAD FIXED VERSION
- **CurseForge:** [1.18.2](https://www.curseforge.com/minecraft/mc-mods/waterframes/files/5305775) | [1.19.2](https://www.curseforge.com/minecraft/mc-mods/waterframes/files/5305778) | [1.20.1](https://www.curseforge.com/minecraft/mc-mods/waterframes/files/5305784)
