### ISSUE TITLE
JEI covers menu

### ISSUE THREAD

**Issue by ProGoofster** [SrRapero720/WATERFrAMES#43]
![2024-04-13_20 12 35](https://github.com/SrRapero720/watermedia/assets/59934842/f1f67a2b-bcb5-496d-822c-3b0de4e08418)

**Comment by SrRapero720** [comment]
issue trasnfered to waterframes because the reported mod is WATERFrAMES, not WATERMeDIA

**Comment by SrRapero720** [comment]
issue was fixed by @CreativeMD in creativecore... will be closed when i release waterframes 2.0 for 1.18.2 - 1.20.1 (and CMD also releases the CC backport)

but this seems to be fixed in 1.20.1 on pre-releases of waterframes

**Comment by SrRapero720** [comment]
## ISSUE ADDRESSED, DOWNLOAD FIXED VERSION
- **CurseForge:** [1.18.2](https://www.curseforge.com/minecraft/mc-mods/waterframes/files/5305775) | [1.19.2](https://www.curseforge.com/minecraft/mc-mods/waterframes/files/5305778) | [1.20.1](https://www.curseforge.com/minecraft/mc-mods/waterframes/files/5305784)
