### ISSUE TITLE
Images causes a large fps drop, spams log

### ISSUE THREAD

**Issue by lolLucoa** [SrRapero720/WATERFrAMES#45]
title. spams this in logs: 
`[Render thread/INFO] [mojang/GlDebug]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Cannot access buffer data.'`

**Comment by lolLucoa** [comment]
still happens on latest version `PRE-RELEASE 2.0.0-pre.3`

**Comment by SrRapero720** [comment]
Issue addressed on WATERMeDIA
