### ISSUE TITLE
Server Crashing Upon Start-Up [Server Blames WaterFrames]

### ISSUE THREAD

**Issue by ChiesyCake** [SrRapero720/WATERFrAMES#47]
Minecraft Version: 1.20.1
Forge Version: 47.2.30 (Latest available on Shockbyte)
WaterFrames Version: 2.0.0-pre.4 (Also tested 1.3.1e and had same results)

[crash-2024-04-30_03.44.18-fml.txt](https://github.com/SrRapero720/waterframes/files/15157680/crash-2024-04-30_03.44.18-fml.txt)
[latest.log](https://github.com/SrRapero720/waterframes/files/15157681/latest.log)

Sorry in advance if this issue is not caused by WaterFrames and is something else, I am not skilled in reading crash logs and the log blamed WaterFrames so I decided to leave a crash report here. It is worth noting that I tested with different versions of WaterMedia and CreativeCore as well, but always had the server crash on me. If there are any details I left out that you need please let me know and I'll add them, cheers.

**Comment by SrRapero720** [comment]
## ISSUE ADDRESSED, DOWNLOAD FIXED VERSION
- **CurseForge:** [1.18.2](https://www.curseforge.com/minecraft/mc-mods/waterframes/files/5305775) | [1.19.2](https://www.curseforge.com/minecraft/mc-mods/waterframes/files/5305778) | [1.20.1](https://www.curseforge.com/minecraft/mc-mods/waterframes/files/5305784)
