### ISSUE TITLE
1.18.2 Version requires newer version of CreativeCore

### ISSUE THREAD

**Issue by crassmister** [SrRapero720/WATERFrAMES#51]
Version 2.0.1 & 2.0.0 requires the 1.20.4 version of CreativeCore. When 1.18.2 versions of creativecore are loaded, waterframes crashes.
Details:
	Mod File: /C:/Users/agony/curseforge/minecraft/Instances/Gregory I shat my pants/mods/waterframes-1.18.2-2.0.0.jar
	Failure message: Mod waterframes requires creativecore 2.11.27 or above
		Currently, creativecore is not installed
	Mod Version: 2.0.0
	Mod Issue URL: https://github.com/SrRapero720/waterframes/issues
	Exception message: MISSING EXCEPTION MESSAGE

**Comment by brisingraerowing** [comment]
Also affects 1.19.2.

**Comment by SrRapero720** [comment]
READ THE CHANGELOG

**Comment by brisingraerowing** [comment]
The changelog doesn't reference **CreativeCore**, it has a reference to **Create**.

[This line is the issue](https://github.com/SrRapero720/waterframes/blob/1.18.2/gradle.properties#L48). You are requiring the 1.20.1 version of CreativeCore on both 1.18.2 and 1.19.2.

**Comment by SrRapero720** [comment]
![image](https://github.com/SrRapero720/waterframes/assets/29090346/c45993e4-dfe0-4417-9abd-3e996e1d7802)

**Comment by brisingraerowing** [comment]
Didn't see that. Derp.

EDIT: That's only in the 2.0.0 Changelog. I didn't see the Waterframes update until after 2.0.1 was released, and that text isn't there. I suspect others may be in the same situation. I also don't look at the CF website for mods, I use the app.
