### ISSUE TITLE
Occasionally, WaterFrames requires a CreativeCore version that is impossible to install on 1.19.2

### ISSUE THREAD

**Issue by TheOnlyOsh** [SrRapero720/WATERFrAMES#52]
![image_2024-05-02_193216262](https://github.com/SrRapero720/waterframes/assets/164664907/9f17c23c-7fbb-45f7-af9b-8eed20f67382)
![image](https://github.com/SrRapero720/waterframes/assets/164664907/037fcbde-c5f5-4035-9c01-38db54f5b34f)

This only happens sometimes I have no idea why

**Comment by SrRapero720** [comment]
read the changelog
