### ISSUE TITLE
Stellarity incompatibility (wont fix)

### ISSUE THREAD

**Issue by SrRapero720** [SrRapero720/WATERFrAMES#53]
## This Issue for the record
Stellarity is a datapack made by @kohy-creates which adds a bunch of stuff on the end dimension.

## Cause
The author for _some unexplained reason_ decides to modify the minecraft core tex_color shader using the resourcepack of the datapack
https://github.com/kohy-creates/Stellarity/blob/master/resource_pack/assets/minecraft/shaders/core/position_tex_color.fsh

This shader is used by WaterFrames, LittleFrames and VideoPlayer. With this modification, those mods lost the capability of modify the shader color and the transparency and of course picture got rotated (depending on the direction) and cropped.

## Solution
**Nothing on the listed mods side can be done to fix the incompatibility**.
This needs to be addressed by the Stellarity author, removing that shader override or fixing it

## Precautions
To avoid users install both mods and get confused of why WF isn't working properly (and not forcing them to break their worlds removing one of the mods later) waterframes will throw an exception when stellarity is installed, indicating the reason and forcing the user to remove waterframes or remove stellarity before deploy their worlds to producction

**Comment by SrRapero720** [comment]
This issue has been "fixed", whoever, i keep the stellarity crash even on modern versions by 2 reasons
- No interest from the stellarity author to fix + backport the issue fix
- Other mods such as LittleFrames and VideoPlayer are still affected.

VideoPlayer includes now their custom crashes and LittleFrames has pending add it.
And no, new renderer cannot be ported to these mods because it was a little bit experimental and behavior cross-versions is unknowed. not even mentioning the 1.18.2~1.21.1 support range

**Comment by uczpre** [comment]
nullscape is best end mod :D
