### ISSUE TITLE
Add Sound Physics Remastered Support?

### ISSUE THREAD

**Issue by V00D00M** [SrRapero720/WATERFrAMES#55]
Wondered if it was at all possible to add in support for Sound Physics Remastered, because if you want a dedicated room to watch films, you can clearly hear the stream in that x amount of block radius set to the tv. That way for those who use the mod, the audio would be muffled to those who are outside the room/area of the stream. Just figured it could be a nice feature to add onto the mod. Y'all are doing an amazing job, keep up the great work!!

**Comment by SrRapero720** [comment]
see #50
