### ISSUE TITLE
Game keeps crashing after 2.0.2 update in 1.20.1 forge version.

### ISSUE THREAD

**Issue by lynariel** [SrRapero720/WATERFrAMES#56]
Since I updated the Waterframes mod, game crashing at loading map. The message in the minecraft launcher is : 

" The game crashed whilst ticking block entity
Error: java.lang.IllegalArgumentException: Cannot set property IntegerProperty{name=power, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]} to -2147483648 on Block{waterframes:frame}, it is not an allowed value "

I downgraded the mod to 2.0.1 and deleted all the waterframes in my solo world then updated to 2.0.2 and keeps crashing with the same message. 

[crash-2024-05-04_22.35.33-server.txt](https://github.com/SrRapero720/waterframes/files/15210947/crash-2024-05-04_22.35.33-server.txt)

Thanks in advance to your support.

**Comment by SrRapero720** [comment]
fixed
