### ISSUE TITLE
My friends game crashes when we load anything on the television

### ISSUE THREAD

**Issue by Pendragon000** [SrRapero720/WATERFrAMES#59]
In a 1.20.1 Forge server one of my friends game keeps crashing everytime we put something on the television.
Its weird because its only him that crash while all of us the mod works perfectly
Here is the error that the minecraft launcher gives him:
The game crashed whilst ticking block entity
Error: java.lang.NoSuchMethodError: 'long me.srrapero720.watermedia.api.math.MathAPI.tickToMs(long)'
I also added his crash report
[crash-2024-05-06_21.49.36-client.txt](https://github.com/SrRapero720/waterframes/files/15228466/crash-2024-05-06_21.49.36-client.txt)

**Comment by SrRapero720** [comment]
update watermedia
