### ISSUE TITLE
Support for live video

### ISSUE THREAD

**Issue by super-bunny** [SrRapero720/WATERFrAMES#6]
Hello, do you plan to support live video like YouTube live or Twitch?

**Comment by SrRapero720** [comment]
is already supported, we found a bug breaking Twitch support on WATERMeDIA related with VLC. we fixed it in the next WMedia release

**Comment by SrRapero720** [comment]
Fixed in 1.3.1b
https://www.curseforge.com/minecraft/mc-mods/waterframes/files/4594867
https://www.curseforge.com/minecraft/mc-mods/watermedia/files/4594373

This version requires WATERMeDIA over 1.2.0 and below 1.3.0
