### ISSUE TITLE
[1.19.2] Requires CreativeCore 2.11.27 which doesn't exists

### ISSUE THREAD

**Issue by XtoManuel** [SrRapero720/WATERFrAMES#60]
Current 2.0.X versions require a CreativeCore version equal to or higher than version 2.11.27, but currently for Forge version 1.19.2, the highest CreativeCore version is 2.9.4.

```cmd
[07may2024 13:47:50.843] [main/ERROR] [net.minecraftforge.fml.loading.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
	Mod ID: 'creativecore', Requested by: 'waterframes', Expected range: '[2.11.27,)', Actual version: '2.9.3'
```

**Comment by DxsSucuk** [comment]
Can confirm, thhe latest version of waterframes requires a version of creativecore which is not released for 1.19.2

**Comment by SrRapero720** [comment]
https://github.com/SrRapero720/CreativeCore/releases/

**Comment by SrRapero720** [comment]
Version 2.11.27 is now available for 1.18.2
1.19.2 is pending

**Comment by kitovoi111** [comment]
> Version 2.11.27 is now available for 1.18.2 1.19.2 is pending

[crash-2024-05-28_05.11.19-fml.txt](https://github.com/SrRapero720/waterframes/files/15463077/crash-2024-05-28_05.11.19-fml.txt)
))))+

**Comment by kitovoi111** [comment]
ambientsounds mod no working in your version CreativeCore

**Comment by SrRapero720** [comment]
thats why i am backporting the whole CreativeMD mods to the 1.19.2... to get all mods working with that version of CreativeCore...

**Comment by kitovoi111** [comment]
> thats why i am backporting the whole CreativeMD mods to the 1.19.2... to get all mods working with that version of CreativeCore...

Can you please send me the corrected version of AmbientSounds?

**Comment by kitovoi111** [comment]
1.19.2 Forge need

**Comment by kitovoi111** [comment]
AmbientSound fixed no ?

**Comment by SrRapero720** [comment]
ambientsounds is fixed yes
i just need to finish 4 mods

**Comment by SrRapero720** [comment]
version is released
https://www.curseforge.com/minecraft/mc-mods/creativecore/files/5491926

**Comment by kitovoi111** [comment]
> version is released https://www.curseforge.com/minecraft/mc-mods/creativecore/files/5491926

![image](https://github.com/user-attachments/assets/dcc5fc9a-f5bf-407f-a340-ff77dc249e12)
