### ISSUE TITLE
waterframe 1.18.2 requires forge 40.2.15 but i have the 40.2.4

### ISSUE THREAD

**Issue by tealtoxic** [SrRapero720/WATERFrAMES#63]
[16:04:16] [main/ERROR] [ne.mi.fm.lo.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
        Mod ID: 'forge', Requested by: 'waterframes', Expected range: '[40.2.15,41)', Actual version: '40.2.4'
        
 can pls add support for forge 40.2.4 please? tq

**Comment by brisingraerowing** [comment]
Why not just upgrade Forge?

**Comment by SrRapero720** [comment]
i will not add support for 40.2.4

just upgrade forge...
