### ISSUE TITLE
Issue between versions on 1.19.2 | The latest version of WaterFrames with CreativeCore.

### ISSUE THREAD

**Issue by GabrielFl4** [SrRapero720/WATERFrAMES#65]
The latest version of WaterFrames for **1.19.2 (2.0.5)** requires Creative Core **v2.11.27** or above. The issue is... there's no CreativeCore above **v2.9.4** for **1.19.2**. At least, not on CurseForge and Modrinth.
I'm I being dumb and didn't realise something I should? Sorry is that's the case.

By the way, CurseForge asked me to update to the last version of WaterFrames, which is **v2.0.5**.
..
![image](https://github.com/SrRapero720/waterframes/assets/75579401/61ff562a-fab5-4a0d-a7ab-b4919f3387e3)
![image](https://github.com/SrRapero720/waterframes/assets/75579401/24b77fcf-7792-4c68-9774-939ae53d77ac)

**Thanks for the Attention!**

**Comment by SrRapero720** [comment]
see #60
