### ISSUE TITLE
Black Screen on Mac when using videos

### ISSUE THREAD

**Issue by JustAiden9** [SrRapero720/WATERFrAMES#69]
When I have a frame with a video/gif in it, the frame just does not play anything. I installed VLC on my Mac, and that fixed the no VLC bug, but now it is just a black frame.

**Comment by JustAiden9** [comment]
Ok it works sometimes, but then it just freezes the video after playing it once.

**Comment by SrRapero720** [comment]
# 🗃️ I NEED YOUR LOGS TO DIAGNOSE
Your latest.log file is placed in your ``.minecraft/logs`` folder (instance folder), pickup the file and upload it into any website below. 
If your game crashes please also append the crash report in the ``.minecraft/crash-report`` folder.
Paste it here so i can help you more easier

# 🖥️ PASTE PAGES
- **Github (100MB)**: https://gist.github.com/
- **MCLogs (10MB)**: https://mclo.gs/
- **PasteGG (15MB)**: https://paste.gg/
- **PasteEE (1MB)**: https://paste.ee/
- **HasteBin (400kB)**: https://hastebin.com/
- **CentOS (1MB)**: https://paste.centos.org/

**Comment by JustAiden9** [comment]
I am able to play short videos and some 5 minute videos, but like a 20 minute video will not load. It loads on my Windows PC, but not on the Mac. It might be a CPU issue, but correct me if I am wrong.
[LOGS](https://gist.github.com/JustAiden9/d3583ff5b063f258a0d323280a96e6fe)

**Comment by JustAiden9** [comment]
Oh also I don't crash, I just left after getting the logs.

**Comment by SrRapero720** [comment]
Mac carries _a lot_ of minor issues that are out of my hands, video loading is one of them.
Is planned a _option to prevent that_ but not a specific fix. So my suggestion is use windows to get the full experience
(again, i can't fix it, because is a problem of MacOS/VLC and not directly of WATERMeDIA)
