### ISSUE TITLE
[Fabric 1.20.1 alpha.6] Unable to "put down" UI elements

### ISSUE THREAD

**Issue by Draconad** [SrRapero720/WATERFrAMES#74]
Unsure how else to describe it, everything else works fine, but when you open a screen or projector to alter things such as size, brightness or screen placement, after clicking into the respective slider or box it then becomes impossible to put it back down again meaning its virtually impossible to select the desired position.

**Comment by SrRapero720** [comment]
See #70

**Comment by SrRapero720** [comment]
now released
https://www.curseforge.com/minecraft/mc-mods/creativecore/files/5379149
