### ISSUE TITLE
Add the feature to disable light and emissive

### ISSUE THREAD

**Issue by afawe3331** [SrRapero720/WATERFrAMES#76]
They should be able to be disabled.

**Comment by SrRapero720** [comment]
is already in serverconfig

**Comment by afawe3331** [comment]
> is already in serverconfig

Nice, but it would be cool to be able to set ON OFF via GUI for each display.

**Comment by SrRapero720** [comment]
That's not possible.
Hot plug light will cause a bunch of issues.

**Comment by afawe3331** [comment]
> That's not possible. Hot plug light will cause a bunch of issues.

While it may not be possible to turn lights off and on, it is possible to turn emissive off and on. Check out the toggle emissive feature in this mod.
https://www.curseforge.com/minecraft/mc-mods/online-displays

**Comment by SrRapero720** [comment]
moved to #73
