### ISSUE TITLE
resort

### ISSUE THREAD

**Issue by HakureiReim09** [SrRapero720/WATERFrAMES#77]
Unable to use the fetch protocol video link directly captured in the browser

**Comment by SrRapero720** [comment]
more info? link? logs?

**Comment by HakureiReim09** [comment]
> 更多信息？链接？原木？

https://cn-jsyz-ct-03-50.bilivideo.com/live-bvc/716072/live_525334813_11714148.flv?expires=1717967604&pt=web&deadline=1717967604&len=0&oi=0x240e03281d35ce0088b88d4b8bb2877f&platform=web&qn=0&trid=100048a383e897a54f25a08c08dc93211a52&uipk=100&uipv=100&nbs=1&uparams=cdn,deadline,len,oi,platform,qn,trid,uipk,uipv,nbs&cdn=cn-gotcha01&upsig=877c6b9d1fca03f6d3c66d9f4861596c&sk=1d78f669e43fe5bf6a49b690fc81818b&p2p_type=1&sl=1&free_type=0&mid=1557728147&sid=cn-jsyz-ct-03-50&chash=1&bmt=1&sche=ban&score=1&pp=rtmp&freeze=1&source=onetier&trace=119&site=9d9091ccbc32e23abe37cfe5d4917f27&qp=de_0&zoneid_l=151339009&sid_l=stream_name_cold&order=1
This crawled link cannot be used

**Comment by HakureiReim09** [comment]
> > 更多信息？链接？原木？
> 
> https://cn-jsyz-ct-03-50.bilivideo.com/live-bvc/716072/live_525334813_11714148.flv?expires=1717967604&pt=web&deadline=1717967604&len=0&oi=0x240e03281d35ce0088b88d4b8bb2877f&platform=web&qn=0&trid=100048a383e897a54f25a08c08dc93211a52&uipk=100&uipv=100&nbs=1&uparams=cdn,deadline,len,oi,platform,qn,trid,uipk,uipv,nbs&cdn=cn-gotcha01&upsig=877c6b9d1fca03f6d3c66d9f4861596c&sk=1d78f669e43fe5bf6a49b690fc81818b&p2p_type=1&sl=1&free_type=0&mid=1557728147&sid=cn-jsyz-ct-03-50&chash=1&bmt=1&sche=ban&score=1&pp=rtmp&freeze=1&source=onetier&trace=119&site=9d9091ccbc32e23abe37cfe5d4917f27&qp=de_0&zoneid_l=151339009&sid_l=stream_name_cold&order=1 无法使用此已爬网链接

This crawled link cannot be used

**Comment by HakureiReim09** [comment]
> > 更多信息？链接？原木？
> 
> https://cn-jsyz-ct-03-50.bilivideo.com/live-bvc/716072/live_525334813_11714148.flv?expires=1717967604&pt=web&deadline=1717967604&len=0&oi=0x240e03281d35ce0088b88d4b8bb2877f&platform=web&qn=0&trid=100048a383e897a54f25a08c08dc93211a52&uipk=100&uipv=100&nbs=1&uparams=cdn,deadline,len,oi,platform,qn,trid,uipk,uipv,nbs&cdn=cn-gotcha01&upsig=877c6b9d1fca03f6d3c66d9f4861596c&sk=1d78f669e43fe5bf6a49b690fc81818b&p2p_type=1&sl=1&free_type=0&mid=1557728147&sid=cn-jsyz-ct-03-50&chash=1&bmt=1&sche=ban&score=1&pp=rtmp&freeze=1&source=onetier&trace=119&site=9d9091ccbc32e23abe37cfe5d4917f27&qp=de_0&zoneid_l=151339009&sid_l=stream_name_cold&order=1 无法使用此已爬网链接

This link can be used in the middle of adding network flows in VLC

**Comment by SrRapero720** [comment]
Investigating
Bill video splits video and audio so maybe your url will not be heared

 not sure what you mean with Network flows, so I am not sure how to proceed
