### ISSUE TITLE
 I hope to be able to play videos from the Bilibili website within the game.

### ISSUE THREAD

**Issue by yunyuyuyn** [SrRapero720/WATERFrAMES#78]
bilibili.com

**Comment by SrRapero720** [comment]
Sadly your website splits the audio and the video
So the experience might be not the most ideal

You can, but extracting the m3u8 link, and depending of what you extract it can be the audio or the video

**Comment by yunyuyuyn** [comment]
I cannot capture the m3u8 link; I can only obtain this link. I hope to learn how you obtain the m3u8.

https://upos-sz-mirrorcos.bilivideo.com/upgcxcode/66/21/1057102166/1057102166-1-192.mp4?e=ig8euxZM2rNcNbNzhwdVhwdlhbhVhwdVhoNvNC8BqJIzNbfq9rVEuxTEnE8L5F6VnEsSTx0vkX8fqJeYTj_lta53NCM=&uipk=5&nbs=1&deadline=1719513865&gen=playurlv2&os=coso1bv&oi=2584261250&trid=4217723cbdec4ca4966bdb1c9aa91838O&mid=0&platform=html5&og=cos&upsig=6612a66e9247cd54dacca53ea0dc4a11&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform,og&bvc=vod&nettype=1&orderid=0,3&buvid=&build=7330300&f=O_0_0&bw=230737&logo=80000000
