### ISSUE TITLE
Crash when opening creative inventory.

### ISSUE THREAD

**Issue by Gwen-Del** [SrRapero720/WATERFrAMES#82]
<ins>Game version :</ins> 1.20.1
<ins>Forge version :</ins> 47.3.0
<ins>Waterframes version :</ins> 2.0.10
<ins>Watermedia version :</ins> 2.0.66

The crash only occurs in multiplayer and not in single-player. 
I play on a server with many mods, so the crash may not have been caused by this mod.
When I open my creative inventory, the client crashes (not the server).

```
net.minecraftforge.fml.ModLoadingException: WaterFrames (waterframes) encountered an error during the done phase
§7java.lang.NullPointerException: Registry Object not present: waterframes:remote
```
(Yes, it's in french so I translated the sentence here)

### Crash report :
[crash-2024-07-09_16.58.12-client.txt](https://github.com/user-attachments/files/16145375/crash-2024-07-09_16.58.12-client.txt)

**Comment by SrRapero720** [comment]
your error says waterframes item is missing
and you're connected on a multiplayer server

error is about waterframes is missing on your server
which is very weird, you shouldn't be hable to connect into a server if the server doesn't have WF

**Comment by Gwen-Del** [comment]
I've remade an empty server and I've put the mods back on and I no longer have the problem. I don't think it's the mod, I must have made a mistake the first time.
