### ISSUE TITLE
audio nor visual work on frames

### ISSUE THREAD

**Issue by kelpster-kj** [SrRapero720/WATERFrAMES#83]
Hi! I have multiple friends on a server that have this issue where they can not see or hear videos when played on frames! 

The server uses 

CreativeCore - 2.11.30
VideoPlayer - 2.6.2
WaterFrame - 1.20.1-2.0.9
WaterMedia - 2.0.58
 
and runs on
1.20.1 forge

I'd love to be able to watch videos with these friends in game so if anyone could help me find a fix for this issue that would be great!

**Comment by SrRapero720** [comment]
update all the mods you listed including MinecraftForge

**Comment by kelpster-kj** [comment]
Okay thank you! will bring this up with the owners of the server!!
