### ISSUE TITLE
Fabric 1.20.1 - YT video in server is played very fast

### ISSUE THREAD

**Issue by Josuburga** [SrRapero720/WATERFrAMES#84]
As the title says, a YT video in a server is played really fast, not in the normal speed. This doesn't happen with Twitch streams or local videos. And the issue is just in server, it doesn't happen in singleplayer (even though in client/server I see the YT videos in a low quality, but that's other story)

The server uses:

CreativeCore 2.11.30
WATERMeDIA 2.0.66
Video Player 2.6.1
WATERFrAMES 2.0.11a

https://github.com/user-attachments/assets/0c29c41e-bace-4ef1-b773-d06f5f8cb95b

**Comment by SrRapero720** [comment]
is the 1.21?
i need info about the modloader, version of the ML,

**Comment by Josuburga** [comment]
> is the 1.21?

It's 1.20.1, loader 0.15.11

**Comment by Steven-OConnell** [comment]
Can confirm this happens with any streamed video file (excluding live streams).

There is also insane log spam from CreativeCore any time the frame interface is opened.
`[15:46:11] [Render thread/WARN]: [REI] Screen team.creative.creativecore.common.gui.integration.ContainerScreenIntegration did not render background and foreground! This might cause rendering issues!`

[latest.log](https://github.com/user-attachments/files/16203721/latest.log)

This is a server only issue and does not appear on Single player.

MC ver 1.20.1
Fabric ver 0.15.11

WATERFrAMES ver 2.0.11a
WATERMeDIA ver 2.0.66
CreativeCore ver 2.11.30

**Comment by SrRapero720** [comment]
yeah i am dumb enough to hook a server side handler using a method that only exists on client-side :P
new update is pending, for now, go back to WF beta (i will release the update in a few hours)

**Comment by Steven-OConnell** [comment]
Damn that was fast, I wasn't expecting to get a follow up for at least a few days.
Awesome mod BTW, great work. XD

**Comment by SrRapero720** [comment]
Fixed
curseforge download: https://www.curseforge.com/minecraft/mc-mods/waterframes/files/5530573
modrinth download: https://modrinth.com/mod/waterframes/version/FABRIC-mc1.20.1-v2.0.11b

**Comment by Josuburga** [comment]
> Fixed curseforge download: https://www.curseforge.com/minecraft/mc-mods/waterframes/files/5530573 modrinth download: https://modrinth.com/mod/waterframes/version/FABRIC-mc1.20.1-v2.0.11b

Ok so I confirm that now it works well, but with this version now there seems to be an overloading and "Overloading cleared" messages in the log of the server. Just in case I came back to the previous version (2.0.11a) and that doesn't happen, it's with this new version.  

[latest.log](https://github.com/user-attachments/files/16215868/latest.log)

**Comment by SrRapero720** [comment]
see #86 is fixed

**Comment by dan2m** [comment]
This has been happening on Forge 1.20.1 as well

MC 1.20.1
Forge 47.3.0

WATERFrAMES ver 2.0.11a
WATERMeDIA ver 2.0.66
CreativeCore ver 2.11.31
