### ISSUE TITLE
Log spam issue.

### ISSUE THREAD

**Issue by Steven-OConnell** [SrRapero720/WATERFrAMES#86]
Currently the log is being spammed with two "warning" category entries.

The first will spam continuously while loaded into a world;
`[Server thread/WARN]: Overloading cleared`

The second shows up when a screen/frame interface is opened.
`[Render thread/WARN]: [REI] Screen team.creative.creativecore.common.gui.integration.ContainerScreenIntegration did not render background and foreground! This might cause rendering issues!`

[latest.log](https://github.com/user-attachments/files/16215991/latest.log)

MC ver 1.20.1
Fabric ver 0.15.11

WATERFrAMES ver 2.0.11b
WATERMeDIA ver 2.0.66
CreativeCore ver 2.11.30

_Side note: As the second log entry appears to be related to Creative Core, should I also open an Issue on the [CreativeCore](https://github.com/CreativeMD/CreativeCore/issues) repo as well?_

**Comment by Steven-OConnell** [comment]
For the time being I'm using [Log Begone](https://modrinth.com/mod/log-begone) to suppress the spam as the warnings seem benign in nature.

**Comment by Josuburga** [comment]
I'm having the same issue as well, same MC, loader and mod versions (well, except of REI because I don't use it). However in my case in the log sometimes it appears as if there was a real overloading.

[latest.log](https://github.com/user-attachments/files/16216147/latest.log)

**Comment by SrRapero720** [comment]
First log spam was my issue (sorry)
second one was caused by JEI, not creativecore

JEI has a weird concern about the screens of CC, (concern that should NOT HAVE) open an issue on JEI repo, not to CC

**Comment by SrRapero720** [comment]
fix is now uploaded

CURSEFORGE
https://legacy.curseforge.com/minecraft/mc-mods/waterframes/files/5531904

MODRINTH
https://modrinth.com/mod/waterframes/version/FABRIC-mc1.20.1-v2.0.11c
