### ISSUE TITLE
Issues with updating to new Waterframes Version

### ISSUE THREAD

**Issue by Patadorea** [SrRapero720/WATERFrAMES#89]
We tried to update your mod on our server from 1.20.1-2.0.10 to v2.0.11a and we could had issues with the version change for our server with existing water frames blocks. We received an error along the lines of "The power value for the projector was 16 and the valid values were [0, 1, 2, 3... 15]". At this point the server has been around for a long time so we don't know how many projectors exist or where they all are. Is there another way for us to update, or a possible fix without removing all existing projectors, frames and tvs? Thank you! We really appreciate your work and your mod is beloved by our small smp of friends, no rush or anything I am just passionate to play your updated version.

**Comment by SrRapero720** [comment]
downgrade to 2.0.9, i am working on a fix

**Comment by Patadorea** [comment]
already have for now, tysm! I look forward to it! :>

**Comment by SrRapero720** [comment]
fixed
Forge https://www.curseforge.com/minecraft/mc-mods/waterframes/files/5539609
Fabric https://www.curseforge.com/minecraft/mc-mods/waterframes/files/5539757

**Comment by Patadorea** [comment]
Ty you are awesome!!
