### ISSUE TITLE
Breaking the mod's blocks don't drop any items

### ISSUE THREAD

**Issue by SxRHunter** [SrRapero720/WATERFrAMES#90]
Fabric waterframes v2.0.12
Also breaking the block is slow with the pickaxe

**Comment by SrRapero720** [comment]
someday i will adivinate the version of minecraft

**Comment by SxRHunter** [comment]
Woops it's 1.21 sorry about that

**Comment by SrRapero720** [comment]
fixed
https://www.curseforge.com/minecraft/mc-mods/waterframes/files/5541793
