### ISSUE TITLE
Server Crashes when uploading a video

### ISSUE THREAD

**Issue by Minoacidsd** [SrRapero720/WATERFrAMES#91]
Hola, tengo una duda sobre si la dependencia de Watermedia (2.0.66) es necesaria que esté instalada en el servidor para funcionar, o solo por parte del cliente? He estado jugando en la versión Forge-1.20.1-47.3.0- con WaterFrames v2.0.11a y el servidor crashea al colocar un video principalmente diciendo que hubo "Ticking block entity" - The entity 'waterframes:frame' at the location 240, 78, -1535 is causing issues while ticking.

Alguna forma de solucionarlo?

**Comment by SrRapero720** [comment]
solo parte del cliente es necesario watermedia, en el servidor no se instala
sobre tu crash, ya lo arregle, checa en CURSEFORGE la version mas reciente (Actualizate mijo)
