### ISSUE TITLE
Problem with the frame for image

### ISSUE THREAD

**Issue by BreastFire** [SrRapero720/WATERFrAMES#94]
Hi, i can´t craft the object for images or gifs, but i can get it with the OP menu

Java 1.20.1 Fabric

Version 1.20.1-2.0.10-beta.1

![Screenshot_29](https://github.com/user-attachments/assets/777f7ae9-f2c9-4ee6-a178-0a6ef0bdbc4b)

**Comment by SrRapero720** [comment]
Update to 2.0.14
