### ISSUE TITLE
Waterframe demands watermedia in server

### ISSUE THREAD

**Issue by uczpre** [SrRapero720/WATERFrAMES#95]
lol

**Comment by uczpre** [comment]
using latest 1.20.1 version

pls dont give that goofy ah "Uhhh i dont support that version , pls use latest version" response.
1.20.1 is still the version most mods support , infact its the highest version awesome mods like create , valkyrien skies , eureka airships , and simple animated guns support. its a bad idea to not support 1.20.1 , especially since most people who want such cursed mods tend to also prefer other cursed mods like the ones i just mentioned.

thanks ;D

**Comment by SrRapero720** [comment]
dude... chill... i literally release an update for 1.20.1 like... 2 days ago. I AM STILL FUCKING SUPPORTING 1.18.2
for fabric, put watermedia on server too, fabric has a limitation that doesn't let me have sided dependencies as forge/neoforge does (fabric is idiotic)

**Comment by uczpre** [comment]
oh no im not mad , im as chill as ice dude.
why would i be mad at someone as sweet and kind like you ? <3

in which case you should change the description on the watermedia page , modpack creators section.

**Comment by uczpre** [comment]
im sorry if i came off as rude. im just used to devs saying that , i simply wrote that for convinience's sake.
didnt the "lol" imply that im slightly amused ?
